// ============================================================================
// QUERY DE VALIDAÇÃO - INTEGRIDADE DE RELACIONAMENTOS
// ============================================================================
// Objetivo: Validar integridade referencial entre tabelas de fato e dimensões
// Data: 2026-02-03
// Fase: 3 - Validação de Medidas
// ============================================================================

// ============================================================================
// TESTE 1: Vendas sem Produto (Órfãos)
// ============================================================================

EVALUATE
CALCULATETABLE(
    SUMMARIZECOLUMNS(
        'Vendas Total AXIA'[ID_PRODUTO],
        "QTD_Registros", COUNTROWS('Vendas Total AXIA'),
        "VLR_Total", SUM('Vendas Total AXIA'[VLR_TOTAL])
    ),
    ISBLANK('Dim Produto AXIA'[ID_PRODUTO])
)

// Resultado esperado: Tabela vazia (sem órfãos)
// Se houver resultados: Investigar IDs de produtos inexistentes

// ============================================================================
// TESTE 2: Vendas sem Filial (Órfãos)
// ============================================================================

// EVALUATE
// CALCULATETABLE(
//     SUMMARIZECOLUMNS(
//         'Vendas Total AXIA'[ID_FILIAL],
//         "QTD_Registros", COUNTROWS('Vendas Total AXIA'),
//         "VLR_Total", SUM('Vendas Total AXIA'[VLR_TOTAL])
//     ),
//     ISBLANK('Dim Filiais AXIA'[ID_FILIAL])
// )

// ============================================================================
// TESTE 3: Estoque sem Produto (Órfãos)
// ============================================================================

// EVALUATE
// CALCULATETABLE(
//     SUMMARIZECOLUMNS(
//         'Estoque Atual AXIA'[ID_PRODUTO],
//         "QTD_Registros", COUNTROWS('Estoque Atual AXIA'),
//         "VLR_Estoque", SUM('Estoque Atual AXIA'[VLR_ESTOQUE])
//     ),
//     ISBLANK('Dim Produto AXIA'[ID_PRODUTO])
// )

// ============================================================================
// TESTE 4: Pedidos de Compras sem Produto (Órfãos)
// ============================================================================

// EVALUATE
// CALCULATETABLE(
//     SUMMARIZECOLUMNS(
//         'Pedidos de Compras AXIA'[ID_PRODUTO],
//         "QTD_Registros", COUNTROWS('Pedidos de Compras AXIA'),
//         "VLR_Total", SUM('Pedidos de Compras AXIA'[VLR_TOTAL])
//     ),
//     ISBLANK('Dim Produto AXIA'[ID_PRODUTO])
// )

// ============================================================================
// TESTE 5: Cardinalidade - Produtos sem Vendas (Dimensões não usadas)
// ============================================================================

// EVALUATE
// CALCULATETABLE(
//     SUMMARIZECOLUMNS(
//         'Dim Produto AXIA'[ID_PRODUTO],
//         'Dim Produto AXIA'[DSC_PRODUTO],
//         "Tem_Vendas", NOT(ISBLANK([VLR Vendas Total])),
//         "Tem_Estoque", NOT(ISBLANK([VLR Estoque Total]))
//     ),
//     AND(
//         ISBLANK([VLR Vendas Total]),
//         ISBLANK([VLR Estoque Total])
//     )
// )

// Resultado: Produtos sem movimentação (candidatos à remoção ou análise)

// ============================================================================
// TESTE 6: Validação de Datas - Registros fora do Calendário
// ============================================================================

// EVALUATE
// CALCULATETABLE(
//     SUMMARIZECOLUMNS(
//         'Vendas Total AXIA'[DAT_EMISSAO],
//         "QTD_Registros", COUNTROWS('Vendas Total AXIA')
//     ),
//     ISBLANK('Dim Calendário'[Data])
// )

// ============================================================================
// NOTAS DE VALIDAÇÃO
// ============================================================================
// - Execute cada teste individualmente (descomente um por vez)
// - Resultado esperado para testes 1-4: Tabelas vazias (sem órfãos)
// - Teste 5: Identifica produtos inativos (pode ter resultados válidos)
// - Teste 6: Identifica datas fora do range do calendário
// - Documente todos os resultados em validation/results/integrity-report.md
