// ============================================================================
// QUERY DE VALIDAÇÃO - DELTA V3 → V2 (Golden Dataset)
// ============================================================================
// Objetivo: Validar que todas as medidas/funcionalidades exclusivas do V3
//           foram corretamente adicionadas ao V2 (que é o Golden Dataset)
// Data: 2026-02-03
// Fase: 3 - Validação de Medidas
// ============================================================================

// IMPORTANTE: 
// - V2 é a BASE (Golden Dataset)
// - V3 tem medidas/tabelas ADICIONAIS que devem ser migradas para V2
// - Esta query valida se a migração foi bem-sucedida

// ============================================================================
// TESTE 1: Verificar Medidas Exclusivas V3 no Golden Dataset (V2)
// ============================================================================

// Execute esta query NO MODELO V2 (Golden Dataset) após migração
// Todas as medidas devem retornar TRUE se foram migradas corretamente

EVALUATE
{
    // Medidas de Estoque Retroativo (Exclusivas V3)
    ("Estoque Retroativo (R$)", NOT(ISERROR([Estoque Retroativo (R$)]))),
    ("Estoque Retroativo (un)", NOT(ISERROR([Estoque Retroativo (un)]))),
    ("Custo médio Retroativo", NOT(ISERROR([Custo médio Retroativo]))),
    
    // Medidas Switch de Unidades (Exclusivas V3)
    ("Vendas (un)", NOT(ISERROR([Vendas (un)]))),
    ("Vendas (Kg/L)", NOT(ISERROR([Vendas (Kg/L)]))),
    ("Vendas (Hec)", NOT(ISERROR([Vendas (Hec)]))),
    ("Vendas (R$)", NOT(ISERROR([Vendas (R$)]))),
    
    // Medidas de Previsão S&OP (Exclusivas V3)
    ("Demanda 60 dias", NOT(ISERROR([Demanda 60 dias]))),
    ("WMAPE", NOT(ISERROR([WMAPE]))),
    ("Erro", NOT(ISERROR([Erro]))),
    
    // Medidas POG (Exclusivas V3)
    ("Estoq. - Fat. Ante. - Xd", NOT(ISERROR([Estoq. - Fat. Ante. - Xd])))
}

// Resultado esperado: Todas as linhas com TRUE
// Se alguma retornar FALSE/ERROR: Medida não foi migrada do V3 para V2

// ============================================================================
// TESTE 2: Comparar Resultados V3 vs V2 (Golden) - Medidas Migradas
// ============================================================================

// Execute esta query PRIMEIRO no V3 (para obter valores de referência)
// Depois execute no V2 (Golden) e compare os resultados
// Diferença esperada: 0% (valores idênticos)

EVALUATE
TOPN(
    50,
    SUMMARIZECOLUMNS(
        'Dim Produto AXIA'[DSC_PRODUTO],
        'Dim Filiais AXIA'[DSC_FILIAL],
        "Estoque_Retro_R$", [Estoque Retroativo (R$)],
        "Estoque_Retro_un", [Estoque Retroativo (un)],
        "Custo_Medio_Retro", [Custo médio Retroativo]
    ),
    [Estoque Retroativo (R$)],
    DESC
)

// Salvar resultados:
// - V3: validation/results/V3_delta_measures_20260203.csv
// - V2: validation/results/V2_delta_measures_20260203.csv
// Comparar: Devem ser IDÊNTICOS

// ============================================================================
// TESTE 3: Validar Tabelas Adicionais do V3
// ============================================================================

// Verificar se tabelas exclusivas do V3 que são úteis foram avaliadas:
// - Dados (1 coluna) - Avaliar necessidade
// - Páginas (2 colunas) - Tabela de navegação
// - Medida (4 colunas) - Verificar se não é duplicata

// Execute no V2 (Golden) para verificar se existem:

// EVALUATE
// ROW(
//     "Tabela_Dados_Existe", NOT(ISERROR(COUNTROWS('Dados'))),
//     "Tabela_Paginas_Existe", NOT(ISERROR(COUNTROWS('Páginas'))),
//     "Tabela_Medida_Existe", NOT(ISERROR(COUNTROWS('Medida')))
// )

// Resultado esperado: Depende da decisão de migração
// Documentar em validation/results/table-migration-decisions.md

// ============================================================================
// TESTE 4: Validar que LocalDateTables NÃO foram migradas
// ============================================================================

// Execute no V2 (Golden) para confirmar que Auto Date/Time está desabilitado
// Deve retornar 0 (zero) tabelas LocalDateTable

EVALUATE
FILTER(
    INFO.TABLES(),
    SEARCH("LocalDateTable", [Name], 1, 0) > 0
)

// Resultado esperado: Tabela vazia (0 LocalDateTables)
// Se houver resultados: Auto Date/Time ainda está ativado (ERRO!)

// ============================================================================
// TESTE 5: Validar Colunas Adicionais do V3
// ============================================================================

// Tabelas com colunas adicionais no V3 que podem ter sido migradas:
// - Dim Calendário: V3 tem +1 coluna (verificar qual e se é necessária)
// - Entradas AXIA: V3 tem +10 colunas (verificar quais e se são necessárias)
// - Faturamentos Antecipados: V3 tem +1 coluna

// Execute no V2 (Golden) para listar colunas de cada tabela:

// EVALUATE
// SELECTCOLUMNS(
//     FILTER(
//         INFO.COLUMNS(),
//         [TableName] = "Dim Calendário"
//     ),
//     "Coluna", [ColumnName],
//     "Tipo", [DataType]
// )

// Comparar com V3 e documentar decisões de migração

// ============================================================================
// CHECKLIST DE VALIDAÇÃO DELTA V3 → V2
// ============================================================================
// 
// [ ] Teste 1: Todas as medidas exclusivas V3 existem no V2 (Golden)
// [ ] Teste 2: Resultados das medidas migradas são idênticos (V3 = V2)
// [ ] Teste 3: Decisão sobre tabelas exclusivas V3 documentada
// [ ] Teste 4: Confirmado que LocalDateTables NÃO existem no V2
// [ ] Teste 5: Colunas adicionais do V3 avaliadas e migradas (se necessário)
// [ ] Documentação completa em validation/results/v3-to-v2-migration.md

// ============================================================================
// NOTAS IMPORTANTES
// ============================================================================
// - V2 é o GOLDEN DATASET (base principal)
// - V3 tem funcionalidades ADICIONAIS que devem ser incorporadas ao V2
// - Após migração, V2 (Golden) deve ter TUDO do V2 original + DELTA do V3
// - V3 NÃO deve ter nada que V2 não tenha (exceto LocalDateTables que devem ser removidas)
// - Validação é V3 → V2, não V2 → V3
