table 'Dim Filiais AXIA'
	lineageTag: 5be34c40-09dc-4bf3-b58f-4dd21ea258f7

	column FILIAL
		dataType: string
		lineageTag: 4778d1cd-1657-402e-acbc-583e623cbe68
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: f7957464-8725-4acf-872f-f4e15e5a94ae
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column IE
		dataType: string
		lineageTag: c1a5d028-2429-45fc-9748-855a3b4a3b11
		summarizeBy: none
		sourceColumn: IE

		annotation SummarizationSetBy = Automatic

	column RZO_SOCIAL
		dataType: string
		lineageTag: 111e1323-88a9-43e7-87a6-078da2b6c439
		summarizeBy: none
		sourceColumn: RZO_SOCIAL

		annotation SummarizationSetBy = Automatic

	column NOM_FANTASIA
		dataType: string
		lineageTag: 1758dc8b-006d-459f-b537-973d55267702
		summarizeBy: none
		sourceColumn: NOM_FANTASIA

		annotation SummarizationSetBy = Automatic

	column RUA
		dataType: string
		lineageTag: 80416807-2b58-44f0-8ff5-c111bd49fea9
		summarizeBy: none
		sourceColumn: RUA

		annotation SummarizationSetBy = Automatic

	column NUMERO
		dataType: string
		lineageTag: 27462562-3d48-4ebe-96b6-282ea072e4a0
		summarizeBy: none
		sourceColumn: NUMERO

		annotation SummarizationSetBy = Automatic

	column COMPLEMENTO
		dataType: string
		lineageTag: dbf28755-4ab2-4967-8d52-5b4eb51eef73
		summarizeBy: none
		sourceColumn: COMPLEMENTO

		annotation SummarizationSetBy = Automatic

	column BAIRRO
		dataType: string
		lineageTag: 3cbc39ca-31f6-44fd-a99d-f34b09d2e5fb
		summarizeBy: none
		sourceColumn: BAIRRO

		annotation SummarizationSetBy = Automatic

	column CEP
		dataType: string
		lineageTag: 77ac8e37-7ddf-4831-b4dd-499f2f9e9885
		summarizeBy: none
		sourceColumn: CEP

		annotation SummarizationSetBy = Automatic

	column LATITUDE
		dataType: string
		lineageTag: a6d91b3a-adb9-4097-a3fb-f4c8d72f879d
		summarizeBy: none
		sourceColumn: LATITUDE

		annotation SummarizationSetBy = Automatic

	column LONGITUDE
		dataType: string
		lineageTag: fd1248a8-c10b-4bf9-88aa-ba2d08140e8e
		summarizeBy: none
		sourceColumn: LONGITUDE

		annotation SummarizationSetBy = Automatic

	column CIDADE
		dataType: string
		lineageTag: 7f709e6e-a2e6-4b81-9aff-0c08894ac56e
		summarizeBy: none
		sourceColumn: CIDADE

		annotation SummarizationSetBy = Automatic

	column COD_IBGE
		dataType: string
		lineageTag: 5d222000-15b1-4773-b738-a91ea49bccd7
		summarizeBy: none
		sourceColumn: COD_IBGE

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 05cd9de9-ae57-4d54-80fe-8303a7a3c329
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	column TELEFONE
		dataType: string
		lineageTag: ff14f298-8573-4992-afb2-7a8ea85d0496
		summarizeBy: none
		sourceColumn: TELEFONE

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: 0e790098-6f97-4f14-a0e7-946f245977e0
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column EMPRESA
		dataType: string
		lineageTag: c2344b19-c5d6-4639-951d-a5899ab81cff
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column CLASSIFICACAO
		dataType: string
		lineageTag: 5df74dbb-64f7-4cf0-b22f-f59d5a60ea93
		summarizeBy: none
		sourceColumn: CLASSIFICACAO

		annotation SummarizationSetBy = Automatic

	column REGIONAL
		dataType: string
		lineageTag: 69af9251-c566-4cfd-bf89-a9c749929fe8
		summarizeBy: none
		sourceColumn: REGIONAL

		annotation SummarizationSetBy = Automatic

	column MATURACAO
		dataType: string
		lineageTag: d2a65530-1280-47fc-b748-b47c70d46aee
		summarizeBy: none
		sourceColumn: MATURACAO

		annotation SummarizationSetBy = Automatic

	column TIPO_LOCACAO
		dataType: string
		lineageTag: 6995e775-0991-4b45-96f2-59faf9667d6d
		summarizeBy: none
		sourceColumn: TIPO_LOCACAO

		annotation SummarizationSetBy = Automatic

	column DATA_INSERCAO
		dataType: string
		lineageTag: 5501a7de-6da8-427b-adbf-d7f0ca0bad1c
		summarizeBy: none
		sourceColumn: DATA_INSERCAO

		annotation SummarizationSetBy = Automatic

	column FILIAL_EXT
		dataType: string
		lineageTag: 2655af27-7560-4549-8351-ce05651cf2b9
		summarizeBy: none
		sourceColumn: FILIAL_EXT

		annotation SummarizationSetBy = Automatic

	column flg_matriz
		dataType: string
		lineageTag: 97fa3c60-2231-4db4-8b39-ab9bf4c97c8c
		summarizeBy: none
		sourceColumn: flg_matriz

		annotation SummarizationSetBy = Automatic

	column ID_FILIAL
		dataType: string
		lineageTag: 2d83da96-d67b-493f-8f46-192bf666fed4
		summarizeBy: none
		sourceColumn: ID_FILIAL

		annotation SummarizationSetBy = Automatic

	column regional_gerencial
		dataType: string
		lineageTag: df320374-4b0f-4964-a68b-e4a543bb9e41
		summarizeBy: none
		sourceColumn: regional_gerencial

		annotation SummarizationSetBy = Automatic

	column FILIAL_PROTHEUS
		dataType: string
		lineageTag: 25a862d6-a209-40b0-92ac-67e180d07fcc
		summarizeBy: none
		sourceColumn: FILIAL_PROTHEUS

		annotation SummarizationSetBy = Automatic

	column Regional_gerencial_2
		dataType: string
		lineageTag: 0d2ce7d4-8cc8-47d1-b522-6944d83ff940
		summarizeBy: none
		sourceColumn: Regional_gerencial_2

		annotation SummarizationSetBy = Automatic

	column Cluster_Estado
		dataType: string
		lineageTag: 4c3aeb63-f930-43fd-820d-447f023e1636
		summarizeBy: none
		sourceColumn: Cluster_Estado

		annotation SummarizationSetBy = Automatic

	column Filial_planejamento
		dataType: string
		lineageTag: 84221c97-f68f-47d0-81d5-0e8b93f09024
		summarizeBy: none
		sourceColumn: Filial_planejamento

		annotation SummarizationSetBy = Automatic

	column DT_INICIO_VIGENCIA
		dataType: dateTime
		formatString: General Date
		lineageTag: 448e04b1-434e-489b-96eb-642a95737d4c
		summarizeBy: none
		sourceColumn: DT_INICIO_VIGENCIA

		annotation SummarizationSetBy = Automatic

	column DT_FIM_VIGENCIA
		dataType: dateTime
		formatString: General Date
		lineageTag: a90d50db-6b4f-49bb-9173-d62718af0221
		summarizeBy: none
		sourceColumn: DT_FIM_VIGENCIA

		annotation SummarizationSetBy = Automatic

	column FLG_AXIA
		dataType: string
		lineageTag: 484ecc35-130c-4961-9973-1a98f0fe0d19
		summarizeBy: none
		sourceColumn: FLG_AXIA

		annotation SummarizationSetBy = Automatic

	partition 'Dim Filiais AXIA' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("agroops.database.windows.net", "axiapool", [Query="select * from [8_AUX].[DIM_FILIAIS_GERENCIAL]"]),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(Fonte,{{"Filial_planejamento", Text.Proper, type text}, {"CIDADE", Text.Proper, type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colocar Cada Palavra Em Maiúscula", each true),
				    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Linhas Filtradas",{{"EMPRESA", Text.Proper, type text}})
				in
				    #"Colocar Cada Palavra Em Maiúscula1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

