table 'Dim Produto AXIA'
	lineageTag: a5167506-a82c-443b-8660-569294bf02e3

	column ID_Produto
		dataType: string
		lineageTag: ca7984a0-22a9-4544-a53b-05d4b1d15e7d
		summarizeBy: none
		sourceColumn: ID_Produto

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column COD_Protheus
		dataType: string
		lineageTag: 218c9ec3-5c53-47d2-ab17-26b23e23c64b
		summarizeBy: none
		sourceColumn: COD_Protheus

		annotation SummarizationSetBy = Automatic

	column Dsc_Produto
		dataType: string
		lineageTag: 594c7659-a3f3-4c20-8ebd-e86134052f01
		summarizeBy: none
		sourceColumn: Dsc_Produto

		annotation SummarizationSetBy = Automatic

	column Dsc_Unificada
		dataType: string
		lineageTag: b0a8ff57-3266-4897-a5b1-629811eee8e5
		summarizeBy: none
		sourceColumn: Dsc_Unificada

		annotation SummarizationSetBy = Automatic

	column Und_Produto
		dataType: string
		lineageTag: 76d41c09-4b8e-4b2f-8593-b9f05c6a2d8e
		summarizeBy: none
		sourceColumn: Und_Produto

		annotation SummarizationSetBy = Automatic

	column Medida_Produto
		dataType: string
		lineageTag: dbe1d5bb-4355-48e8-a8f4-bd360aacda18
		summarizeBy: none
		sourceColumn: Medida_Produto

		annotation SummarizationSetBy = Automatic

	column COD_Marca
		dataType: int64
		formatString: 0
		lineageTag: 6e06b521-bf4e-4df7-835a-435d15b4fb7e
		summarizeBy: sum
		sourceColumn: COD_Marca

		annotation SummarizationSetBy = Automatic

	column Nom_Marca
		dataType: string
		lineageTag: fd8bf60a-a554-4afc-9c6b-11abdf4746d8
		summarizeBy: none
		sourceColumn: Nom_Marca

		annotation SummarizationSetBy = Automatic

	column COD_Fornecedor
		dataType: int64
		formatString: 0
		lineageTag: ecbe3245-e214-4e79-81c6-e4e4a64b2d96
		summarizeBy: sum
		sourceColumn: COD_Fornecedor

		annotation SummarizationSetBy = Automatic

	column Nom_Fornecedor
		dataType: string
		lineageTag: b5f2a2db-c8e3-493d-aa6a-ce983dfae00b
		summarizeBy: none
		sourceColumn: Nom_Fornecedor

		annotation SummarizationSetBy = Automatic

	column COD_Grupo
		dataType: int64
		formatString: 0
		lineageTag: de8f48ed-6a56-4e5d-b069-44f4ff8baf4f
		summarizeBy: sum
		sourceColumn: COD_Grupo

		annotation SummarizationSetBy = Automatic

	column Dsc_Grupo
		dataType: string
		lineageTag: 9fff377f-4cb9-4a3f-910d-044415a0aa4b
		summarizeBy: none
		sourceColumn: Dsc_Grupo

		annotation SummarizationSetBy = Automatic

	column COD_Subgrupo1
		dataType: int64
		formatString: 0
		lineageTag: c0ad494b-f21f-4ebc-b55f-27f8012e96f3
		summarizeBy: sum
		sourceColumn: COD_Subgrupo1

		annotation SummarizationSetBy = Automatic

	column Dsc_Subgrupo1
		dataType: string
		lineageTag: 5b2367a7-98f7-4540-95de-6145e3c3279b
		summarizeBy: none
		sourceColumn: Dsc_Subgrupo1

		annotation SummarizationSetBy = Automatic

	column COD_Subgrupo2
		dataType: int64
		formatString: 0
		lineageTag: 860e1837-4352-4c70-860b-888105dd1630
		summarizeBy: sum
		sourceColumn: COD_Subgrupo2

		annotation SummarizationSetBy = Automatic

	column Dsc_Subgrupo2
		dataType: string
		lineageTag: e80cc477-4214-483b-b3c8-40c2b3afc006
		summarizeBy: none
		sourceColumn: Dsc_Subgrupo2

		annotation SummarizationSetBy = Automatic

	column COD_Subgrupo3
		dataType: int64
		formatString: 0
		lineageTag: 47c78e67-e75d-49f5-8e6a-5aa3529e8f2d
		summarizeBy: sum
		sourceColumn: COD_Subgrupo3

		annotation SummarizationSetBy = Automatic

	column Dsc_Subgrupo3
		dataType: string
		lineageTag: 19a839a7-9c7a-4c46-8ec4-87c7c05761ab
		summarizeBy: none
		sourceColumn: Dsc_Subgrupo3

		annotation SummarizationSetBy = Automatic

	column Dsc_Grupo_Axia
		dataType: string
		lineageTag: 1c0e00a9-989d-4d72-b134-24699e3af354
		summarizeBy: none
		sourceColumn: Dsc_Grupo_Axia

		annotation SummarizationSetBy = Automatic

	column Peso
		dataType: double
		lineageTag: 6a1e30d0-b515-4e4d-a294-692e16070879
		summarizeBy: sum
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NCM_Produto
		dataType: string
		lineageTag: fbd72e70-7584-4706-b7ac-02805cec2040
		summarizeBy: none
		sourceColumn: NCM_Produto

		annotation SummarizationSetBy = Automatic

	column CEST_Produto
		dataType: string
		lineageTag: 7ae0ae4d-37f4-4a44-adf4-fea8ef3f3f28
		summarizeBy: none
		sourceColumn: CEST_Produto

		annotation SummarizationSetBy = Automatic

	column Dose_Vacina
		dataType: string
		lineageTag: 7b611d00-2371-4dcd-8c8d-8de99dd2dbc3
		summarizeBy: none
		sourceColumn: Dose_Vacina

		annotation SummarizationSetBy = Automatic

	column Und_Conversao_Lt_Hectar
		dataType: string
		lineageTag: bc3d53dc-1603-461f-8d44-488aba386e0f
		summarizeBy: none
		sourceColumn: Und_Conversao_Lt_Hectar

		annotation SummarizationSetBy = Automatic

	column PrincipioATV_Produto
		dataType: string
		lineageTag: a97e24a5-d9a2-45c0-befd-c840d9060025
		summarizeBy: none
		sourceColumn: PrincipioATV_Produto

		annotation SummarizationSetBy = Automatic

	column Concentracao_Produto
		dataType: string
		lineageTag: 1a60651f-8ae8-4f74-915d-ed6fb0892737
		summarizeBy: none
		sourceColumn: Concentracao_Produto

		annotation SummarizationSetBy = Automatic

	column Classificacao_QBR
		dataType: string
		lineageTag: 10623598-1257-4bbb-8ea4-77ca3d49b95f
		summarizeBy: none
		sourceColumn: Classificacao_QBR

		annotation SummarizationSetBy = Automatic

	column Id_Grupo_QBR
		dataType: string
		lineageTag: 40e80244-4874-48e9-8c5d-ece7e9d3b0fb
		summarizeBy: none
		sourceColumn: Id_Grupo_QBR

		annotation SummarizationSetBy = Automatic

	column Grupo_QBR
		dataType: string
		lineageTag: 4d428e18-d23f-4525-be99-4a4dc9a1b223
		summarizeBy: none
		sourceColumn: Grupo_QBR

		annotation SummarizationSetBy = Automatic

	column ID_Patria
		dataType: string
		lineageTag: ff0592e5-1df5-4134-9e95-0a2025c4ddd4
		summarizeBy: none
		sourceColumn: ID_Patria

		annotation SummarizationSetBy = Automatic

	column ID_Sanidade01
		dataType: string
		lineageTag: dbd679b3-7847-48fc-a0b4-bf18639d243f
		summarizeBy: none
		sourceColumn: ID_Sanidade01

		annotation SummarizationSetBy = Automatic

	column Dsc_Sanidade01
		dataType: string
		lineageTag: b4441143-b68a-422c-8664-4f2971108698
		summarizeBy: none
		sourceColumn: Dsc_Sanidade01

		annotation SummarizationSetBy = Automatic

	column ID_Sanidade02
		dataType: string
		lineageTag: b842c1f9-91a1-4063-9411-5f20ce02a9ff
		summarizeBy: none
		sourceColumn: ID_Sanidade02

		annotation SummarizationSetBy = Automatic

	column Dsc_Sanidade02
		dataType: string
		lineageTag: 5a02770a-fe3e-4349-aa86-95f173b35628
		summarizeBy: none
		sourceColumn: Dsc_Sanidade02

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: 96cadd17-dc3f-4297-9ff9-1baffe52c935
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column COD_Barra
		dataType: string
		lineageTag: 884ac1fc-bd19-4212-b9a3-68469ef9088b
		summarizeBy: none
		sourceColumn: COD_Barra

		annotation SummarizationSetBy = Automatic

	column Produto_Ativo
		dataType: string
		lineageTag: f84ebfb7-15af-43b2-8203-751b26b9e09a
		summarizeBy: none
		sourceColumn: Produto_Ativo

		annotation SummarizationSetBy = Automatic

	column Origem
		dataType: string
		lineageTag: 353fbb9c-41b5-4788-a491-da3852842bd6
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	column 'P.A. & Concentração' = 'Dim Produto AXIA'[PrincipioATV_Produto]&" "&'Dim Produto AXIA'[Concentracao_Produto]
		lineageTag: 81350a0f-a3ea-4eb1-ac6f-c0e7cac74a6a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Produto Principal' =
			
			
			if(
			    AND(
			        if(
			            'Dim Produto AXIA'[Dsc_Grupo_Axia]="Defensivos",
			            'Dim Produto AXIA'[P.A. & Concentração],
			                if(
			                    AND('Dim Produto AXIA'[Dsc_Grupo_Axia]="Adubos, Fertilizantes & Corretivos",'Dim Produto AXIA'[P.A. & Concentração]<>" "
			                    ),
			                        'Dim Produto AXIA'[P.A. & Concentração],
			                        if(
			                            AND('Dim Produto AXIA'[Dsc_Grupo_Axia]="Sementes",'Dim Produto AXIA'[Dsc_Subgrupo1]="Pastagem"),
			                                'Dim Produto AXIA'[P.A. & Concentração],
			                                if(
			                                    OR('Dim Produto AXIA'[Dsc_Produto]="Arame Z 700 1.000 Mt",'Dim Produto AXIA'[Dsc_Produto]="Arame Ovalado 1.000 Mt"),
			                                    "Arame Ovalado 1.000 MT",
			                                    'Dim Produto AXIA'[Dsc_Produto])
			                        )
			                )
			        )='Dim Produto AXIA'[P.A. & Concentração],'Dim Produto AXIA'[P.A. & Concentração]=""
			    ),
			        'Dim Produto AXIA'[Dsc_Produto],
			        if('Dim Produto AXIA'[Dsc_Grupo_Axia]="Defensivos",'Dim Produto AXIA'[P.A. & Concentração],
			            if(
			                AND('Dim Produto AXIA'[Dsc_Grupo_Axia]="Adubos, Fertilizantes & Corretivos",'Dim Produto AXIA'[P.A. & Concentração]<>" "
			                ),
			                    'Dim Produto AXIA'[P.A. & Concentração],
			                    if(
			                        AND('Dim Produto AXIA'[Dsc_Grupo_Axia]="Sementes",'Dim Produto AXIA'[Dsc_Subgrupo1]="Pastagem"),
			                        'Dim Produto AXIA'[P.A. & Concentração],
			                        IF(
			                            OR('Dim Produto AXIA'[Dsc_Produto]="Arame Z 700 1.000 Mt",'Dim Produto AXIA'[Dsc_Produto]="Arame Ovalado 1.000 Mt"),
			                            "Arame Ovalado 1.000 MT",
			                            IF (
			                        'Dim Produto AXIA'[Dsc_Produto] IN {
			                            "Brinco Mosquicida Neocidol B-40 (20 Unid.)",
			                            "Brinco Mosquicida Fiprotag 210 (20 Unid)",
			                            "Brinco Mosquicida Expert (20 Un)",
			                            "Brinco Mosquicida Na Mosca (20 Unid.)",
			                            "Brinco Mosquicida Top Tag 180 (20 Unid.)"
			                        },
			                        "Brinco Mosquicida (20 Unid)",
			                        IF (
			                            'Dim Produto AXIA'[Dsc_Produto] IN {
			                                "Brinco Mosquicida Neocidol B-40 (10 Unid.)",
			                                "Brinco Mosquicida Top Tag 180 (10 Unid.)"
			                            },
			                            "Brinco Mosquicida (10 Unid)",
			                            'Dim Produto AXIA'[Dsc_Produto]
			                        )
			                    )
			            )
			        )
			)))
		lineageTag: 8a17032d-d21b-46c2-bcb4-6526bd0ad02c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CHAVE_CLASSIFICACAO
		dataType: string
		lineageTag: 902dfcb0-6f2b-4bfa-b5e4-f124b366a655
		summarizeBy: none
		sourceColumn: CHAVE_CLASSIFICACAO

		annotation SummarizationSetBy = Automatic

	column DFU
		dataType: string
		lineageTag: e20778a7-f7b3-48dc-8460-7d839b5a4c89
		summarizeBy: none
		sourceColumn: DFU

		annotation SummarizationSetBy = Automatic

	column CURVA_PRODUTO
		dataType: string
		lineageTag: bf65ff4d-f753-457f-99b2-2d217420ea6e
		summarizeBy: none
		sourceColumn: CURVA_PRODUTO

		annotation SummarizationSetBy = Automatic

	column curva_produto_old
		dataType: string
		lineageTag: 173cd983-282f-46b2-bdfa-692fc5966ba2
		summarizeBy: none
		sourceColumn: curva_produto_old

		annotation SummarizationSetBy = Automatic

	column classificacao_produto
		dataType: string
		lineageTag: c16ba602-d101-49be-b8f9-c97df9353da2
		summarizeBy: none
		sourceColumn: classificacao_produto

		annotation SummarizationSetBy = Automatic

	column dfu_old
		dataType: string
		lineageTag: f3f28bef-a25a-4bb8-9b1b-695a5670489e
		summarizeBy: none
		sourceColumn: dfu_old

		annotation SummarizationSetBy = Automatic

	column LaboratoriosCentralizados
		dataType: string
		lineageTag: d7bf42f7-85f3-4b84-8958-c8a40c18b6b2
		summarizeBy: none
		sourceColumn: LaboratoriosCentralizados

		annotation SummarizationSetBy = Automatic

	column CONVERSAO_LITRO_CORTEVA
		dataType: double
		lineageTag: 44f06155-859c-4d02-840e-b699ba374048
		summarizeBy: sum
		sourceColumn: CONVERSAO_LITRO_CORTEVA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FATOR_CONVERSAO
		dataType: double
		lineageTag: 37db7a67-c747-445f-8f45-b5ba525ed968
		summarizeBy: sum
		sourceColumn: FATOR_CONVERSAO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UND_MEDIDA_DFU
		dataType: string
		lineageTag: d69af3b5-7dba-41cf-ad66-b918ec6febdf
		summarizeBy: none
		sourceColumn: UND_MEDIDA_DFU

		annotation SummarizationSetBy = Automatic

	column 'Curva Categoria' =
			
			IF(
			    'Dim Produto AXIA'[Produto Principal]="Arame Ovalado 1.000 MT","Curva A",'Dim Produto AXIA'[curva_produto_old]
			)
		lineageTag: 69a3340a-7f7d-4fdc-b04a-28c60960ec37
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Dim Produto AXIA' = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("agroops.database.windows.net", "axiapool", [Query="Select #(lf)T1.* #(lf),t2.Curva_produto as curva_produto_old #(lf),t2.classificacao_produto #(lf),t2.DFU as dfu_old #(lf),t2.LaboratoriosCentralizados #(lf)#(lf)from [4_TMP].[DIM_PRODUTO_AXIA_B] t1#(lf)#(lf)left join [8_AUX].[DIM_PRODUTO_AXIA_DFU] t2#(lf)on t1.ID_PRODUTO = t2.ID_PRODUTO"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Dose_Vacina", type text}}),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"classificacao_produto", Text.Proper, type text}})
				in
				    #"Colocar Cada Palavra Em Maiúscula"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

