table Medidas
	lineageTag: b4f997c1-55ff-4c0b-8333-76a95d5e097f

	measure 'QTD Estoque Bruto' =
			
			IF(SUM('Estoque Atual AXIA'[VLR_ESTOQUE])=0,BLANK(),SUM('Estoque Atual AXIA'[VLR_ESTOQUE]))
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: ff7fb6a7-8df0-457c-82e6-6295b4a7e0ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Atual' =
			
			SUM('Estoque Atual AXIA'[CUSTO_TOTAL])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 2f2c47d4-1361-4222-ac0a-3f2508937e96

	measure 'QTD Estoque Historico' = sum('Estoque Histórico AXIA'[VLR_ESTOQUE])
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: e83aff3e-2ff0-4a63-bdf3-d5bbf4d4543c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Historico' = sum('Estoque Histórico AXIA'[CUSTO_TOTAL])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: f35b40b1-06f6-47fd-94a8-2a06508136a4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Vendas' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[QTD_AJUSTADA_OUTLIER]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: adfacd24-33fb-4cf0-a0f2-6115760666ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Vendas Liquido' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_LIQ_ITEM]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: ad1a1023-9a86-445a-9dc0-87067580892a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Estoque Ano Anterior' = calculate([QTD Estoque Historico],sameperiodlastyear('Dim Calendário'[Date]))
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: 06e58f52-897d-4bcd-84be-b3fa31dc95de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Ano Anterior' = calculate([R$ Estoque Historico],sameperiodlastyear('Dim Calendário'[Date]))
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: e2b6f839-f97c-4198-ba30-d0250037a047

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Custo de Aquisição' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_CUSTO_CMV]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 0e7677f4-6594-4303-bc3a-2088113b7aaf

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Vendas Ano Anterior' = calculate([R$ Vendas Liquido],sameperiodlastyear('Dim Calendário'[Date]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: fdf82b57-8ceb-4115-ae68-b7dc44196ad1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Vendas Ano Anterior' = calculate([QTD Vendas],sameperiodlastyear('Dim Calendário'[Date]))
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: fa56b05f-f86c-4d4e-b225-acdeb69dc362

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Ano Anterior Mes Anterior' = ```
			
			CALCULATE(
			    [R$ Estoque Historico],
			    FILTER(
			        'Estoque Histórico AXIA',
			        'Estoque Histórico AXIA'[DATA_POSICAO] = 
			            EOMONTH(EDATE(TODAY(), -12), -1)   -- volta 1 ano e pega o fim do mês anterior
			    )
			)
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: 18147173-664d-4537-a45d-474d5a7a1bda

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Prox 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,2,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 8dd4e8e8-ef2e-4314-b26f-97c90b4ce704

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 90d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,3,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 3eea2056-05ba-4387-a2ae-f616f8dec877

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 180d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-180,6,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: cb4b5da6-7c31-4ba5-92d7-46aafbbab457

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-60,2,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 35178cf7-3c19-4d53-8e5e-f921268c9fb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 90d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-90,3,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 79acf20a-6a1c-4bcc-bdc7-deefd664c6d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 180d LY' = CALCULATE([QTD Vendas],DATESBETWEEN('Dim Calendário'[Date],today()-(365+180),today()-365))
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 0cfb9528-2b81-4a22-a4c7-ab0f88a849b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ ROB' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_BRUTO_ITEM]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 4ba4f7fe-c6a7-4c83-8ece-0aed350c4e1a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Estoque Liquido' = [QTD Estoque Bruto]-[QTD F.Antecipados]+[QTD Pedidos de Compras Pendentes]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: aab83c70-f897-4369-8809-e8470367a0b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'VW Ultimo Custo Entrada' = CALCULATE(MAX('Entradas AXIA'[VLR_UNIT_ITEM]),LASTDATE('Entradas AXIA'[DATA_EMISSAO]))
		displayFolder: 9.Extra
		lineageTag: 0072dd85-9a29-4be1-96a7-251c6fa34802

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Custo Ult 12 Meses' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,12,MONTH),[R$ Custo de Aquisição])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 134d82a1-ddd3-4baf-bbfc-cf4403b0af6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Filtro Valores' =
			if((
			    [QTD Estoque Bruto]+[QTD Ult 180d])<>0,"Considerar","Desconsiderar")
		displayFolder: 9.Extra
		lineageTag: 48989378-eb91-4aa7-8482-bf6eb1756791

	measure 'DIO por Loja' = ```
			
			
			VAR DIOLoja = 
			DIVIDE(
			    [R$ Estoque Atual],
			    CALCULATE(
			    [R$ Custo de Aquisição],
			    DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        TODAY())
			    ))*365
			
			RETURN
			
			IF(DIOLoja=0,BLANK(),DIOLoja)
			```
		formatString: 0.0
		displayFolder: 4.DIO
		lineageTag: eb5a3dc7-c4cb-4531-a093-cc4da9774c1f

	measure 'Maior DIO entre Lojas' = ```
			
			
			IF(
			    [QTD Estoque Liquido & Compras (Análises)] <> 0 || 
			    
			    CALCULATE(
			    [R$ Custo de Aquisição],
			    DATESBETWEEN(
			    'Dim Calendário'[Date],
			    TODAY() - 365,
			    TODAY())) > 0 ||
			    
			    [QTD Ult 180d LY] <> 0,
			    CALCULATE(
			        MAXX(
			            SUMMARIZE(
			                ALL('Dim Filiais AXIA'),
			                'Dim Filiais AXIA'[Filial_planejamento],
			                "DIO_Valor",
			                    CALCULATE(
			                        [DIO por Loja],
			                        'Dim Produto AXIA'[Produto Principal] = SELECTEDVALUE('Dim Produto AXIA'[Produto Principal])
			                    )
			            ),
			            [DIO_Valor]
			        )
			    ),
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: 4.DIO
		lineageTag: 9786a398-9ce4-4e94-8d51-b2c244b39ea5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Loja com Maior DIO' = ```
			
			IF(
			    [QTD Estoque Liquido & Compras (Análises)] <> 0 || 
			    
			    CALCULATE(
			    [R$ Custo de Aquisição],
			    DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        TODAY())) > 0 ||
			
			    [QTD Ult 180d LY] <> 0,
			    CALCULATE(
			        FIRSTNONBLANK(
			            SELECTCOLUMNS(
			                TOPN(
			                    1,
			                    ADDCOLUMNS(
			                        VALUES('Dim Filiais AXIA'[Filial_planejamento]),
			                        "DIO_Valor",
			                            CALCULATE(
			                                [DIO por Loja],
			                                'Dim Produto AXIA'[Produto Principal] = SELECTEDVALUE('Dim Produto AXIA'[Produto Principal])
			                            )
			                    ),
			                    [DIO_Valor],
			                    DESC
			                ),
			                'Dim Filiais AXIA'[Filial_planejamento]
			            ),
			            1
			        ),
			        REMOVEFILTERS('Dim Filiais AXIA')
			    ),
			    BLANK()
			)
			```
		displayFolder: 4.DIO
		lineageTag: 82c54e40-0a63-430e-9d54-f56fabb616ae

	measure 'DIO por Loja Histórico' =
			
			
			VAR DataFechamentoMes =
			    EOMONTH( MAX('Dim Calendário'[Date]), 0 )   -- fechamento do mês em contexto
			VAR DataInicial =
			    DataFechamentoMes - 364                     -- 365 dias antes (contagem inclusiva)
			RETURN
			DIVIDE(
			    [R$ Estoque Historico],
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        DATESBETWEEN(
			            'Dim Calendário'[Date],
			            DataInicial,
			            DataFechamentoMes
			        )
			    )
			) * 365
		formatString: 0
		displayFolder: 4.DIO
		lineageTag: 0cf194c9-7563-46de-93ff-b6f0eba72ab9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'R$ Vendas CMV' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_CUSTO_CMV]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: a802bdfa-c760-45a7-a665-f0f57d306354

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure EstoqueEmpresa = ```
			
			
			    IF(
			        [R$ Estoque Atual] > 0,
			        CALCULATE(
			            [R$ Estoque Atual],
			            FILTER(
			                ALL('Dim Filiais AXIA'),
			                CALCULATE([R$ Estoque Atual]) > 0
			            )
			        ),
			        BLANK()
			    )
			```
		displayFolder: 9.Extra
		lineageTag: 236f97a0-674c-4b05-ba5e-6b9dcb734ae6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIO por Empresa' =
			
			VAR FiltroPrincipal =
			
			        [QTD Estoque Liquido & Compras (Análises)] <> 0 ||
			
			        CALCULATE(
			        [R$ Custo de Aquisição],
			        DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        TODAY())) > 0 ||
			
			        [QTD Ult 180d LY] <> 0
			
			VAR EstoqueEmpresa =
			    IF(
			        FiltroPrincipal,
			        CALCULATE(
			            [R$ Estoque Atual],
			            ALLEXCEPT('Dim Filiais AXIA', 'Dim Filiais AXIA'[EMPRESA]),
			            'Dim Filiais AXIA'[FLG_AXIA] = "AXIA"
			        )
			    )
			
			VAR DataFinal = TODAY()
			VAR DataInicio = DataFinal - 365
			
			VAR Vendas365 =
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        ALLEXCEPT('Dim Filiais AXIA', 'Dim Filiais AXIA'[EMPRESA]),
			        'Dim Filiais AXIA'[FLG_AXIA] = "AXIA",
			        ALL('Vendas Total AXIA'[DATA_EMISSAO]),
			        DATESBETWEEN(
			            'Vendas Total AXIA'[DATA_EMISSAO],
			            DataInicio,
			            DataFinal
			        )
			    )
			
			RETURN
			IF(
			    FiltroPrincipal && Vendas365 <> 0,
			    ROUND(DIVIDE(EstoqueEmpresa, Vendas365) * 365, 0),
			    BLANK()
			)
		formatString: 0
		displayFolder: 4.DIO
		lineageTag: 37cf4259-54ca-48c0-8a21-17ece4336c65

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DOH Mês Anterior Ano Anterior' = ```
			
			VAR Ano_Mes_Anterior = 
			    EOMONTH(TODAY(), -13)
			VAR Periodo_Ano = 
			    DATESINPERIOD('Dim Calendário'[Date], Ano_Mes_Anterior, -365, DAY)
			
			VAR Custo_de_Aquisicao = 
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        Periodo_Ano
			    )
			
			VAR Estoque_Ano_Mes_Anterior = 
			    CALCULATE(
			        [R$ Estoque Historico],
			        'Dim Calendário'[Date] = Ano_Mes_Anterior
			    )
			
			RETURN
			DIVIDE(Estoque_Ano_Mes_Anterior, Custo_de_Aquisicao) * 365
			```
		displayFolder: 4.DIO
		lineageTag: e8e96517-969e-441f-ba8e-439b7f5a5e09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DOH Mês Anterior Mesmo Ano' = ```
			
			VAR Mes_Anterior = 
			    EOMONTH(TODAY(), -1)
			VAR Periodo_Ano = 
			    DATESINPERIOD('Dim Calendário'[Date], Mes_Anterior, -365, DAY)
			
			VAR Custo_de_Aquisicao = 
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        Periodo_Ano
			    )
			
			VAR Estoque_Mes_Anterior = 
			    CALCULATE(
			        [R$ Estoque Historico],
			        'Dim Calendário'[Date] = Mes_Anterior
			    )
			
			RETURN
			DIVIDE(Estoque_Mes_Anterior, Custo_de_Aquisicao) * 365
			```
		displayFolder: 4.DIO
		lineageTag: 37bfe753-0210-4468-816b-f6a57818c116

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DIO AXIA' = ```
			
			VAR FiltroPrincipal =
			
			        [QTD Estoque Liquido & Compras (Análises)] <> 0 ||
			
			        CALCULATE(
			        [R$ Custo de Aquisição],
			        DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        TODAY())) > 0 ||
			            
			        [QTD Ult 180d LY] <> 0
			
			VAR EstoqueEmpresa =
			    IF(
			        FiltroPrincipal,
			        CALCULATE(
			            [R$ Estoque Atual],
			            ALL('Dim Filiais AXIA'),
			            'Dim Filiais AXIA'[FLG_AXIA] = "AXIA"
			        )
			    )
			
			VAR DataFinal = TODAY()
			VAR DataInicio = DataFinal - 365
			
			VAR Vendas365 =
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        ALL('Dim Filiais AXIA'),
			        'Dim Filiais AXIA'[FLG_AXIA] = "AXIA",
			        ALL('Vendas Total AXIA'[DATA_EMISSAO]),
			        DATESBETWEEN(
			            'Vendas Total AXIA'[DATA_EMISSAO],
			            DataInicio,
			            DataFinal
			        )
			    )
			
			RETURN
			IF(
			    FiltroPrincipal && Vendas365 <> 0,
			    ROUND(DIVIDE(EstoqueEmpresa, Vendas365) * 365, 0),
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: 4.DIO
		lineageTag: ae4c0eb4-b8f9-4603-89b0-6d84aa0a64c6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'QTD F.Antecipados' = SUM('Faturamentos Antecipados AXIA'[QTD_PENDENTE])
		displayFolder: 2.Faturamentos Antecipados
		lineageTag: e592f97b-b271-49b3-b100-3d161f9c640b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SUPORTE_Peso = ```
			
			    IF(
			    [QTD Estoque Liquido & Compras (Análises)] <> 0 || 
			    
			    CALCULATE(
			    [R$ Custo de Aquisição],
			    DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        TODAY())) > 0 ||
			    
			    [QTD Ult 180d LY] <> 0,
			        max('Dim Produto AXIA'[Peso]),
			    BLANK()
			    )
			```
		displayFolder: 9.Extra
		lineageTag: 050cee2b-4a59-44ba-9844-e5e3df322ce4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SUPORTE_QTD Pedido em Aberto' = ```
			
			    IF(
			    [QTD Estoque Liquido] <> 0 || 
			    
			    CALCULATE(
			    [R$ Custo de Aquisição],
			    DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        TODAY())) > 0 ||
			    
			    [QTD Ult 180d LY] > 0,
			        SUM('Pedidos de Compras AXIA'[QTD_PENDENTE_FINAL]),
			    BLANK()
			    )
			```
		displayFolder: 9.Extra
		lineageTag: 567758f9-12c4-4558-abba-44cc2da1b4fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ruptura de Estoque 15d' =
			
			sum(Rupturas[Ruptura 15 dias])
		displayFolder: 1.Estoque\Ruptura
		lineageTag: 181accd0-b9ae-4910-b910-7f8fb6e53fda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ruptura de Estoque 30d' =
			
			sum(Rupturas[Ruptura 30 dias])
		displayFolder: 1.Estoque\Ruptura
		lineageTag: ab8ff9d8-b9b9-4a4e-aeae-98c4b6aed44e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ruptura de Estoque 60d' =
			
			VAR Ruptura_60_Dias = [QTD Estoque Liquido]-SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,60,DAY),[QTD Vendas])
			
			RETURN
			    IF(Ruptura_60_Dias<=0,Ruptura_60_Dias,BLANK())
		displayFolder: 1.Estoque\Ruptura
		lineageTag: e6847059-c995-4fd1-972a-5ec3b53bdca7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Ruptura de Estoque 15d' =
			
			sum(Rupturas[R$ Ruptura 15 dias])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Ruptura
		lineageTag: 36886875-36bc-42a9-835d-f15fc65b6ae9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Ruptura de Estoque 30d' =
			
			sum(Rupturas[R$ Ruptura 30 dias])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Ruptura
		lineageTag: 2f485bfc-10f9-4609-baaa-c63a1fc339a8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ F.Antecipados' = SUM('Faturamentos Antecipados AXIA'[Custo Médio Total])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 2.Faturamentos Antecipados
		lineageTag: 08653c40-7e1b-447f-a2e4-55f23af29102

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Custo Médio Total' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_CUSTO_CMV]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: ad73449c-8e8c-4b59-92d0-785112b7466a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Filtro_Top10_Ruptura =
			
			sum(Rupturas[POG 30 dias])
		displayFolder: 1.Estoque\Ruptura
		lineageTag: c6534867-5af0-4ef1-9997-f37ddc2ec478

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 30d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,1,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 1b8e4647-2061-41dd-8a35-09132e9efaf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Medida = SUM('Pedidos de Compras AXIA'[QUANTIDADE_PENDENTE])
		displayFolder: 9.Extra
		lineageTag: 032472fc-f990-4419-a6d3-1de88d7b301d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 15d' = ROUNDUP(SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,1,MONTH),[QTD Vendas])/2,0)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 05f66a3c-0184-4ee5-a208-cf679dbd4de4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 15d' = ROUNDUP(SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,1,MONTH),[R$ Custo Médio Total])/2,0)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: fa6789f8-15d0-4fe1-a935-7babcd9c5dcc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 30d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,1,MONTH),[R$ Custo Médio Total])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 00ae7bf5-d503-4903-8ecf-886acc656c7c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Estoque Liquido (Análises)' = [R$ Estoque Atual (Análises)]-[R$ F.Antecipados]+[R$ Pedidos de Compras Pendentes]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 3a4a02b5-4f6f-4430-ae09-545dd76ab351

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Relação DIO 24/25' =
			
			1-([DOH Mês Anterior Ano Anterior]/[DOH Mês Anterior Mesmo Ano])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 4.DIO
		lineageTag: 26b07de8-f7a7-42c6-b8a4-b2d4e3834da8

	measure 'R$ Estoque em Vencimento' =
			
			SUM('Estoque Vencimentos AXIA'[CUSTO_TOTAL])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: 2f98772e-63cd-4628-91bb-b0f8368f7686

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Estoque em Vencimento' =
			
			SUM('Estoque Vencimentos AXIA'[QTD_DISP])
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: f1b949d7-a961-4d69-8664-40f0e18f9a1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Estoque Vencido Atual' =
			
			CALCULATE(SUM('Estoque Vencimentos AXIA'[QTD_DISP_KG]),'Estoque Vencimentos AXIA'[DATA_VALIDADE]<=TODAY())
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: 94adcea7-035e-4208-9827-97dd8e68c49f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Vencido Atual' =
			
			CALCULATE(SUM('Estoque Vencimentos AXIA'[CUSTO_TOTAL]),'Estoque Vencimentos AXIA'[DATA_VALIDADE]<=TODAY())
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: 1059db38-0cd3-44cf-a4bb-be7e260745b6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Estoque Vencimento 120 Dias' =
			
			CALCULATE(
			    SUM('Estoque Vencimentos AXIA'[QTD_DISP_KG]),
			    'Estoque Vencimentos AXIA'[Vencimento] IN {"30 dias", "60 dias", "90 dias", "120 dias"}
			)
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: e1adc210-ec21-46e8-b419-773459be46f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Vencimento 120 Dias' =
			
			CALCULATE(
			    SUM('Estoque Vencimentos AXIA'[CUSTO_TOTAL]),
			    'Estoque Vencimentos AXIA'[Vencimento] IN {"30 dias", "60 dias", "90 dias", "120 dias"}
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: 6a2c5b73-07a4-4afa-b711-3339e22d95a2

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Data da Última Compra' =
			
			
			MAX('Entradas AXIA'[DATA_ENTRADA])
		formatString: dd/mm/yyyy
		displayFolder: 9.Extra
		lineageTag: 4e7e4306-09e2-4a28-9a11-41b7b606de17

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Data da Última Venda' =
			
			
			MAX('Vendas Total AXIA'[DATA_EMISSAO])
		formatString: dd/mm/yyyy
		displayFolder: 9.Extra
		lineageTag: 6319ef1a-4464-47e1-98fc-6dcd611e3ea6

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Dias sem Movimentação' =
			
			CALCULATE('Slow Moving AXIA'[Dias Sem Movimentação (Medida)])
		displayFolder: 9.Extra
		lineageTag: 38182d0c-b76a-432c-8830-810b6851964a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Estoque Atual' =
			
			SUM('Estoque Atual AXIA'[VLR_ESTOQUE_KGLT])
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 7e906e79-b8d0-46ea-9674-67b03f84a65d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT F.Antecipados' = SUM('Faturamentos Antecipados AXIA'[QTDPENDENTEPESO])
		displayFolder: 2.Faturamentos Antecipados
		lineageTag: 187fa66c-2a90-4f1f-98ba-ec9a031a9abe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Estoque Historico' = SUM('Estoque Histórico AXIA'[VLR_ESTOQUE_HISTORICO])
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: fccff467-854b-482e-a9ee-574a92077e07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Litros/Kg = SUM('Entradas AXIA'[Litros/Kg])
		displayFolder: 5.Entrada
		lineageTag: de0d4432-29ff-43e3-9ea3-c6f50191205d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Vencimento' = SUM('Estoque Vencimentos AXIA'[QTD_DISP_KG])
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: ad94286b-c883-471d-a322-a0e57d99a617

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Estoque Liquido' = [KGLT Estoque Atual]-[KGLT F.Antecipados]+[KGLT Pedidos de Compras Pendentes]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 901b845e-b1d2-42d6-bc5a-b789c330ef20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Pedidos de Compras Pendentes' =
			
			SUM('Pedidos de Compras AXIA'[QTD_PENDENTE_FINAL])
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 500ccb06-1592-4a53-b5bd-76318d74d3ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Pedidos de Compras Pendentes' =
			
			SUM('Pedidos de Compras AXIA'[KGLT_PENDENTE_FINAL])
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 4d184f7d-9abb-4390-b573-cd59e75d1de2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Pedidos de Compras Pendentes' =
			
			SUM('Pedidos de Compras AXIA'[CUSTO_PENDENTE_FINAL])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 2a97a53b-f2ea-493c-b992-d029feedaed9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Estoque Vencimento 30 Dias' =
			
			CALCULATE(
			    SUM('Estoque Vencimentos AXIA'[CUSTO_TOTAL]),
			    'Estoque Vencimentos AXIA'[Vencimento] IN {"30 dias"}
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: d0a3b1c5-44a0-45a7-b73f-05e95bae35ed

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Estoque Vencimento 90 Dias' =
			
			CALCULATE(
			    SUM('Estoque Vencimentos AXIA'[CUSTO_TOTAL]),
			    'Estoque Vencimentos AXIA'[Vencimento] IN {"30 dias", "60 dias", "90 dias"}
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: 831f3236-35c1-452f-807e-bcfcd6080d5a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure PorcentagemCurva/Categoria =
			
			([R$ Estoque Atual]/[R$ Estoque Ano Anterior Mes Anterior])-1
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 9.Extra
		lineageTag: b756f7df-07a2-419b-bf89-57694e69b876

	measure 'DOH Mês Anterior Ano Anterior 2 (VENDAS)' = ```
			
			VAR Ano_Mes_Anterior = 
			    EOMONTH(TODAY(), -13)
			VAR Periodo_Ano = 
			    DATESINPERIOD('Dim Calendário'[Date], Ano_Mes_Anterior, -365, DAY)
			
			VAR Custo_de_Aquisicao = 
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        Periodo_Ano
			    )
			
			VAR Estoque_Ano_Mes_Anterior = 
			    CALCULATE(
			        [R$ Estoque Historico],
			        'Dim Calendário'[Date] = Ano_Mes_Anterior
			    )
			
			RETURN
			//DIVIDE(Estoque_Ano_Mes_Anterior, Custo_de_Aquisicao) * 365
			Custo_de_Aquisicao
			```
		displayFolder: 4.DIO
		lineageTag: 9d4f1cc3-a5f4-446a-bde5-63fefa6769b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DOH Mês Anterior Ano Anterior 2 (ESTOQUE)' = ```
			
			VAR Ano_Mes_Anterior = 
			    EOMONTH(TODAY(), -13)
			VAR Periodo_Ano = 
			    DATESINPERIOD('Dim Calendário'[Date], Ano_Mes_Anterior, -365, DAY)
			
			VAR Custo_de_Aquisicao = 
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        Periodo_Ano
			    )
			
			VAR Estoque_Ano_Mes_Anterior = 
			    CALCULATE(
			        [R$ Estoque Historico],
			        'Dim Calendário'[Date] = Ano_Mes_Anterior
			    )
			
			RETURN
			//DIVIDE(Estoque_Ano_Mes_Anterior, Custo_de_Aquisicao) * 365
			Estoque_Ano_Mes_Anterior
			```
		displayFolder: 4.DIO
		lineageTag: d5cf2e8c-66e3-4875-8a69-7c355f95316b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DOH Mês Anterior Ano Anterior 2 (DATA)' = ```
			
			VAR Ano_Mes_Anterior = 
			    EOMONTH(TODAY(), -13)
			VAR Periodo_Ano = 
			    DATESINPERIOD('Dim Calendário'[Date], Ano_Mes_Anterior, -365, DAY)
			
			VAR Custo_de_Aquisicao = 
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        Periodo_Ano
			    )
			
			VAR Estoque_Ano_Mes_Anterior = 
			    CALCULATE(
			        [R$ Estoque Historico],
			        'Dim Calendário'[Date] = Ano_Mes_Anterior
			    )
			
			RETURN
			//DIVIDE(Estoque_Ano_Mes_Anterior, Custo_de_Aquisicao) * 365
			Periodo_Ano
			```
		formatString: General Date
		displayFolder: 4.DIO
		lineageTag: 61cd5539-3289-4bb2-bd57-0ef75b6d96c3

	measure 'R$ Estoque Atual (Análises)' = ```
			
			VAR EstoqueAtualRS = 
			CALCULATE(
			    SUM('Estoque Atual AXIA'[CUSTO_TOTAL]),
			    FILTER('Estoque Atual AXIA','Estoque Atual AXIA'[COD_ALOCACAO] <> "80 vencidos/avariados")
			)
			RETURN
			IF(EstoqueAtualRS>0,EstoqueAtualRS,BLANK())
			```
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 674aa5ec-a423-4a0c-8c20-f45611e79471

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Estoque Bruto (Análises)' = ```
			
			VAR EstoqueBruto = 
			CALCULATE(
			    SUM('Estoque Atual AXIA'[VLR_ESTOQUE]),
			    'Estoque Atual AXIA'[COD_ALOCACAO] <> "80 vencidos/avariados"
			)
			
			RETURN
			
			IF(EstoqueBruto=0,BLANK(),EstoqueBruto
			)
			```
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 2a5a9167-17d0-43f4-aba5-76403cbb9f98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Estoque Atual (Análises)' =
			
			CALCULATE(
			    SUM('Estoque Atual AXIA'[VLR_ESTOQUE_KGLT]),
			    'Estoque Atual AXIA'[COD_ALOCACAO] <> "80 vencidos/avariados"
			)
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 240217fb-015e-4953-8de4-e55427162282

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Estoque Liquido (Análises)' = [QTD Estoque Bruto (Análises)]-[QTD F.Antecipados]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 0af767a7-4fd5-40b0-bfb6-2999d467c55f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 120d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,4,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 63aec2d6-8d58-4643-803f-71e984cd4319

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 150d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,5,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: db7757d2-0aff-48d5-b078-a90d00a33f62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 180d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,6,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: ee7ec7f3-982a-4eba-ad66-163624e757bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Demanda S&OP/Protheus 60d' = ```
			
			VAR Periodo = 3
			
			VAR Venda_Prox_Periodo_LY = 
			    SUMX(
			        DATESINPERIOD(
			            'Dim Calendário'[Date],
			            DATE(year(MAX('Dim Calendário'[Date]))-1,MONTH(MAX('Dim Calendário'[Date])),1),
			            Periodo,
			            MONTH
			        ),
			        [QTD Vendas]
			    )
			
			VAR Venda_Ult_Periodo_LY = 
			    SUMX(
			        DATESINPERIOD(
			            'Dim Calendário'[Date],
			            date(year(MAX('Dim Calendário'[Date]))-1,MONTH(MAX('Dim Calendário'[Date]))-Periodo,1),
			            Periodo,
			            MONTH
			        ),
			        [QTD Vendas]
			    )
			    
			VAR Venda_Ult_Periodo_Atual = 
			   SUMX(
			        DATESINPERIOD(
			            'Dim Calendário'[Date],
			            date(year(MAX('Dim Calendário'[Date])),MONTH(MAX('Dim Calendário'[Date]))-Periodo,1),
			            Periodo,
			            MONTH
			        ),
			        [QTD Vendas]
			    )
			
			VAR Crescimento = 
			    IF(ABS(
			    IF(
			        Venda_Ult_Periodo_LY = 0, 
			        BLANK(), 
			        DIVIDE(
			            (Venda_Ult_Periodo_Atual - Venda_Ult_Periodo_LY),
			            Venda_Ult_Periodo_LY
			        )
			    ))>0.7,
			    BLANK(),
			    IF(
			        Venda_Ult_Periodo_LY = 0, 
			        BLANK(), 
			        DIVIDE(
			            (Venda_Ult_Periodo_Atual - Venda_Ult_Periodo_LY),
			            Venda_Ult_Periodo_LY
			        )
			    )
			    )
			
			VAR Media_Venda = 
			    DIVIDE(
			        (Venda_Prox_Periodo_LY + Venda_Ult_Periodo_Atual), 
			        2
			    )
			
			VAR Previsao_Mensal = 
			  
			        Media_Venda * (1 + Crescimento)
			     
			RETURN Previsao_Mensal
			```
		lineageTag: c76fd234-ac4c-4f83-93a0-7a51546fac43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orçamentos Aprovados - Pedidos Recebidos' =
			
			SUM('Aprovações Financeiras'[VLR_ORCAMENTO])-SUM('Pedidos de Compras AXIA'[CUSTO_RECEBIDO_FINAL])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 86b38403-d4a7-4c29-b3ae-fee59942c64e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'KGLT Pedidos de Compras Pendentes (Mês Atual)' =
			
			
			CALCULATE(
			    SUM('Pedidos de Compras AXIA'[KGLT_PENDENTE_FINAL]),
			    KEEPFILTERS(
			        FILTER(
			            'Pedidos de Compras AXIA',
			            YEAR('Pedidos de Compras AXIA'[DATA_PREV_ENTREGA]) = YEAR(TODAY()) &&
			            MONTH('Pedidos de Compras AXIA'[DATA_PREV_ENTREGA]) = MONTH(TODAY())
			        )
			    )
			)
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 7236b0e7-c81e-4748-8457-8d5262aa246a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Pedidos de Compras Pendentes (Mês Atual & Próx. Mês)' =
			
			
			CALCULATE(
			    SUM('Pedidos de Compras AXIA'[KGLT_PENDENTE_FINAL]),
			    KEEPFILTERS(
			        FILTER(
			            'Pedidos de Compras AXIA',
			            'Pedidos de Compras AXIA'[DATA_PREV_ENTREGA] >= DATE(YEAR(TODAY()), MONTH(TODAY()), 1) &&
			            'Pedidos de Compras AXIA'[DATA_PREV_ENTREGA] <= EOMONTH(TODAY(), 1)
			        )
			    )
			)
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: c69e447c-8901-4801-a753-992cfad2816f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Pedidos de Compras Pendentes (Mês Atual & Próx. 2 Meses)' =
			
			
			CALCULATE(
			    SUM('Pedidos de Compras AXIA'[KGLT_PENDENTE_FINAL]),
			    KEEPFILTERS(
			        FILTER(
			            'Pedidos de Compras AXIA',
			            'Pedidos de Compras AXIA'[DATA_PREV_ENTREGA] >= DATE(YEAR(TODAY()), MONTH(TODAY()), 2) &&
			            'Pedidos de Compras AXIA'[DATA_PREV_ENTREGA] <= EOMONTH(TODAY(), 2)
			        )
			    )
			)
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 84c9007d-4562-4252-bf1e-1e79bc15a052

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Vendas' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[KGLT_DISP]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 1c754dc1-86a3-4d8a-8c38-6a034a85707a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,2,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 9ca1ebd1-3ba3-4117-8203-10a6d987d142

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 90d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,3,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: d0075b2a-b869-4ad6-8a47-93dad06a7959

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Ult Ano até Dez' =
			
			CALCULATE(
			    [KGLT Vendas],
			    DATESBETWEEN(
			        'Dim Calendário'[Date],
			        TODAY() - 365,
			        DATE(YEAR(TODAY()) - 1, 12, 31)
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: b6625a23-bdbe-4bce-b810-b183c85f7794

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Previsão S&OP 60d' =
			
			[KGLT Estoque Liquido]-[KGLT Prox 60d]
		displayFolder: 8.S&OP\Previsões
		lineageTag: 73d1a76b-3f6d-47a0-9cfd-595fed0fafd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Previsão S&OP 90d' =
			
			[KGLT Estoque Liquido]-[KGLT Prox 90d]
		displayFolder: 8.S&OP\Previsões
		lineageTag: 8cd37eca-84e5-4930-a408-a807e205000a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Vendas CMV Unitário' =
			
			SUM('Vendas Total AXIA'[VLR_CUSTO_CMV])/SUM('Vendas Total AXIA'[QTD_DISP])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 9cd2676b-bbde-4cb2-a141-b3779213b081

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Custo Médio Unitário' =
			
			VAR CM = [R$ Estoque Atual (Análises)]/[QTD Estoque Bruto (Análises)]
			RETURN
			IF(AND([QTD Estoque Bruto (Análises)]<>0,CM>0),CM,BLANK())
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 8.S&OP\Previsões
		lineageTag: 39a70e12-2bcd-42ca-b3b1-36b62d580a6a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Último VLR_BRUTO_UNIT_ITEM' =
			
			CALCULATE(
			    MAX('Entradas AXIA'[VLR_UNIT_BRUTO_ITEM]),
			    FILTER(
			        'Entradas AXIA',
			        'Entradas AXIA'[DATA_ENTRADA] = 'Entradas AXIA'[Data da Última Compra])
			    )
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: b2f57356-3946-4fc0-be5e-894381748e63

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Entrada Unitário' =
			
			SUM('Entradas AXIA'[VLR_UNIT_BRUTO_ITEM])
		displayFolder: 5.Entrada
		lineageTag: 1dc63588-16b3-4c8e-a131-a31c4adba994

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Pedidos de Compras Pendentes Unitário' =
			
			DIVIDE(
			    SUM('Pedidos de Compras AXIA'[CUSTO_PENDENTE_FINAL]),
			    SUM('Pedidos de Compras AXIA'[QTD_PENDENTE_FINAL])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 076b7b50-ebe2-4bcd-91b1-9e47227fd6dd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'QTD Estoque Liquido & Compras (Análises)' = [QTD Estoque Bruto (Análises)]-[QTD F.Antecipados]+[QTD Pedidos de Compras Pendentes]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 036f3097-ab74-412d-9c09-821ad38d5657

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DOH Mês Anterior Mesmo Ano2222' = ```
			
			VAR Mes_Anterior = 
			    EOMONTH(TODAY(), -1)
			VAR Periodo_Ano = 
			    DATESINPERIOD('Dim Calendário'[Date], Mes_Anterior, -365, DAY)
			
			VAR Custo_de_Aquisicao = 
			    CALCULATE(
			        [R$ Custo de Aquisição],
			        Periodo_Ano
			    )
			
			VAR Estoque_Mes_Anterior = 
			    CALCULATE(
			        [R$ Estoque Historico],
			        'Dim Calendário'[Date] = Mes_Anterior
			    )
			
			RETURN
			//DIVIDE(Estoque_Mes_Anterior, Custo_de_Aquisicao) * 365
			Estoque_Mes_Anterior
			```
		lineageTag: 56512148-2939-4a40-9f52-bfb9991e8c25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ ROB YTD' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_BRUTO_ITEM]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			            && 'Vendas Total AXIA'[DATA_EMISSAO] >= DATE(YEAR(TODAY()), 1, 1)
			            && 'Vendas Total AXIA'[DATA_EMISSAO] <= TODAY()
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: f71c9cb1-a92d-4e14-8c7a-18b6db73f4d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ ROB YTD LY' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_BRUTO_ITEM]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			            && 'Vendas Total AXIA'[DATA_EMISSAO] >= DATE(YEAR(TODAY())-1, 1, 1)
			            && 'Vendas Total AXIA'[DATA_EMISSAO] <= EDATE(TODAY(), -12)
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: f2cf2d0a-a059-4356-8abe-a7f6ce11104e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ CMV YTD' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_CUSTO_CMV]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			            && 'Vendas Total AXIA'[DATA_EMISSAO] >= DATE(YEAR(TODAY()), 1, 1)
			            && 'Vendas Total AXIA'[DATA_EMISSAO] <= TODAY()
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 2da56d02-131e-4497-9564-86416adbc368

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ CMV LY' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_CUSTO_CMV]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			            && 'Vendas Total AXIA'[DATA_EMISSAO] >= DATE(YEAR(TODAY())-1, 1, 1)
			            && 'Vendas Total AXIA'[DATA_EMISSAO] <= EDATE(TODAY(), -12)
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 73404ed8-7fd5-4a4d-a9da-56765137b53d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Relação ROB' =
			
			([R$ ROB YTD]/[R$ ROB YTD LY])-1
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: c9aa29f5-47a7-4513-ad6a-7997df25a106

	measure 'Relação CMV' =
			
			([R$ CMV YTD]/[R$ CMV LY])-1
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: c3234604-fc81-4d6e-9f9e-d4e70dea1bfa

	measure 'Relação CMV - ROB' =
			
			[Relação CMV]-[Relação ROB]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: c945668c-897c-4bf1-9edb-f55b0b477f8e

	measure 'R$ Prox 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,2,MONTH),[R$ ROB])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 3ae4e8dd-0714-40b9-a5ee-23717e01a2d7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Prox 120d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-365,4,MONTH),[R$ ROB])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: fed8f266-71bd-49a1-838f-28f1fa71df69

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Estoque Mês Anterior' = ```
			
			CALCULATE(
			    [R$ Estoque Historico],
			    FILTER(
			        'Estoque Histórico AXIA',
			        'Estoque Histórico AXIA'[DATA_POSICAO] = 
			            EOMONTH(TODAY(), -1)   -- último dia do mês anterior ao atual
			    )
			)
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Histórico
		lineageTag: 5438e796-2f76-488c-8ec0-1c171c5c59b3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Slow Moving 180-360' =
			
			CALCULATE(
			    SUM('Slow Moving AXIA'[CUSTO_TOTAL]),
			        FILTER(
			            'Slow Moving AXIA',
			            'Slow Moving AXIA'[Classificação Slow Moving] = "Entre 180 e 360 dias"
			        )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 9.Extra
		lineageTag: 34ee7ea0-02ff-456a-ab11-b0d247c6a7ec

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Slow Moving >360' =
			
			CALCULATE(
			    SUM('Slow Moving AXIA'[CUSTO_TOTAL]),
			        FILTER(
			            'Slow Moving AXIA',
			            'Slow Moving AXIA'[Classificação Slow Moving] = ">360 dias"
			        )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 9.Extra
		lineageTag: 85dd5db6-caee-42df-924b-dfdac80acdcd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Perda Real Lançada' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[VLR_BRUTO_ITEM]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[CFOP]="5927"
			    )
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 9.Extra
		lineageTag: ef7b1346-9dfa-4272-8d50-a1ecd917943d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'R$ Estoque Vencido Mes Anterior' =
			
			CALCULATE(
			    [R$ Estoque em Vencimento],
			    FILTER(
			        'Estoque Vencimentos AXIA',
			        'Estoque Vencimentos AXIA'[DATA_VALIDADE] >= EOMONTH(TODAY(), -2) + 1
			        && 'Estoque Vencimentos AXIA'[DATA_VALIDADE] <= EOMONTH(TODAY(), -1)
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: 1.Estoque\Estoque Vencimento
		lineageTag: 6485c612-01c6-42cf-aa3a-2fac1bec0ca7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Ruptura 30 Dias R$' =
			
			VAR Ruptura30D = [R$ Estoque Mês Anterior]-'Medidas'[R$ F.Antecipados]-'Medidas'[R$ Prox 30d]+'Medidas'[R$ Pedidos de Compras Pendentes]
			RETURN
			IF(Ruptura30D>=0,BLANK(),(Ruptura30D)
			)
		displayFolder: 8.S&OP\Previsões
		lineageTag: fd9b4b53-c152-4e84-9ddd-f16ef1ae03f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 30d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,1,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 771559fb-d332-4b55-b296-6b9352088ff9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 60d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,2,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 93272759-16ab-432c-af8d-ac653888b181

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 90d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,3,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: aa263562-803f-4b3c-a97d-c211cf1cd883

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 120d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,4,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: e48558d5-b67c-4db3-ae2e-d16ccb1b7bfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 150d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,5,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: f61475ea-f809-4b79-8221-d0f577ac598e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Prox 180d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,6,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: a59e8128-31d7-474e-bc8b-f6d2fbb18a55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 60d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-60,2,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 7fad0d29-3db6-4932-874c-a70b56557db5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 90d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-90,3,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: acb3684b-1e0e-4230-8596-c5dfdbfa97da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Out Diário 15D (R$)' =
			
			--CALCULATE(
			    SUM('Ruptura Diário'[RUPTURA_15D_CUSTO])--,
			--    FILTER('Ruptura AXIA',
			--    'Ruptura AXIA'[QUANTIDADE_ESTOQUE]=0
			--    )
			--)
		displayFolder: 8.S&OP\Previsões
		lineageTag: 71b8bcfc-d6a5-4b7d-be02-c5476b3a674d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Out Diário 30D (R$)' =
			
			CALCULATE(
			    SUM('Ruptura Diário'[RUPTURA_30D_CUSTO_MENOS15D]),
			    FILTER('Rupturas AXIA',
			    'Rupturas AXIA'[QUANTIDADE_ESTOQUE]=0
			    )
			)
		displayFolder: 8.S&OP\Previsões
		lineageTag: f7235f0e-c852-41f9-92ca-53e52e2a594a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ruptura Diário 15D (R$)' =
			
			SUM('Ruptura Diário'[RUPTURA_15D_CUSTO])
		displayFolder: 8.S&OP\Previsões
		lineageTag: a7d691d7-f49e-4806-bab4-d8fd9aad12ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ruptura Diário 30D-15D (R$)' =
			
			SUM('Ruptura Diário'[RUPTURA_30D_CUSTO_MENOS15D])
		displayFolder: 8.S&OP\Previsões
		lineageTag: 1d72afae-d202-4a72-9610-cdd9cc7986ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Out Percentual' =
			
			VAR Percentual = ([Stock Out Diário 30D (R$)]/[Stock Out Diário 30D D-1 (R$)])-1
			RETURN
			Percentual
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 8.S&OP\Previsões
		lineageTag: 177dbe1a-8fb6-40f0-a5c4-54698a1763e6

	measure 'Ruptura Diário 30D D-1 (R$)' =
			
			SUM('Ruptura Diário'[RUPTURA_30D_CUSTO_ANTERIOR])
		displayFolder: 8.S&OP\Previsões
		lineageTag: ae0329b0-b0d9-4a8f-89dc-564248874ef2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Out Diário 30D D-1 (R$)' =
			
			CALCULATE(
			    SUM('Ruptura Diário'[RUPTURA_30D_CUSTO_ANTERIOR]),
			    FILTER('Rupturas AXIA',
			    'Rupturas AXIA'[QUANTIDADE_ESTOQUE]=0
			    )
			)
		displayFolder: 8.S&OP\Previsões
		lineageTag: a3ebfd59-1188-46d8-8581-6fd5ee445c35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QTD Ult 120d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-120,4,MONTH),[QTD Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 1e53bc62-0a34-477b-92dc-b0a13f2c20ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SWITCH Estoque Bruto (Análises)' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[QTD Estoque Bruto (Análises)],
			    "R$",[R$ Estoque Atual (Análises)],
			    "kg/Lt",[KGLT Estoque Atual (Análises)],
			    "Hec",[HEC Estoque Bruto (Análises)]
			)
		formatString: 0.00
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 54d9d0c1-e622-4058-b063-83f84420b9ad

	measure 'HEC Estoque Bruto (Análises)' =
			
			VAR SwitchHec =
			CALCULATE(
			    SUMX(
			        'Estoque Atual AXIA',
			        VAR txt =
			            TRIM(
			                SUBSTITUTE(
			                    RELATED('Dim Produto AXIA'[Und_Conversao_Lt_Hectar]), ",", "."
			                )
			            )
			        VAR num = IFERROR( VALUE( txt ), BLANK() )
			        RETURN
			            IF(
			                NOT ISBLANK(num) && num > 0,
			                'Estoque Atual AXIA'[VLR_ESTOQUE_KGLT] / num,
			                BLANK()
			            )
			    ),
			    'Estoque Atual AXIA'[COD_ALOCACAO] <> "80 vencidos/avariados",
			    'Dim Produto AXIA'[Nom_Marca] = "Corteva"
			)
			RETURN
			IF( SwitchHec > 0, SwitchHec, BLANK() )
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: bb224cd8-d677-4180-ace5-b851f768d056

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HEC F.Antecipados' =
			
			VAR SwitchHec =
			 CALCULATE(
			    SUMX(
			        'Faturamentos Antecipados AXIA',
			        VAR txt =
			            TRIM(
			                SUBSTITUTE(
			                    RELATED('Dim Produto AXIA'[Und_Conversao_Lt_Hectar]), ",", "."
			                )
			            )
			        VAR num = IFERROR( VALUE( txt ), BLANK() )
			        RETURN
			            IF( NOT ISBLANK(num) && num > 0,
			                'Faturamentos Antecipados AXIA'[QTDPENDENTEPESO] / num,
			                BLANK()
			            )
			    ),
			    'Dim Produto AXIA'[Nom_Marca] = "Corteva"
			)
			RETURN
			IF( SwitchHec > 0, SwitchHec, BLANK() )
		displayFolder: 2.Faturamentos Antecipados
		lineageTag: e25c9220-7956-44d5-a2cc-5d512c02a5e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SWITCH F. Antecipados' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[QTD F.Antecipados],
			    "R$",[R$ F.Antecipados],
			    "kg/Lt",[KGLT F.Antecipados],
			    "Hec",[HEC F.Antecipados]
			)
		formatString: 0.00
		displayFolder: 2.Faturamentos Antecipados
		lineageTag: 408e3960-4e2f-47dd-8ac9-e4815aefaf44

	measure 'HEC Vendas' =
			
			VAR SwitchHec =
			CALCULATE(
			    SUMX(
			        'Vendas Total AXIA',
			        VAR txt =
			            TRIM(
			                SUBSTITUTE(
			                    RELATED('Dim Produto AXIA'[Und_Conversao_Lt_Hectar]), ",", "."
			                )
			            )
			        VAR num = IFERROR( VALUE( txt ), BLANK() )
			        RETURN
			            IF(
			                NOT ISBLANK(num) && num > 0,
			                'Vendas Total AXIA'[KGLT_DISP] / num,
			                BLANK()
			            )
			    ),
			    'Dim Produto AXIA'[Nom_Marca] = "Corteva"
			)
			RETURN
			IF( SwitchHec > 0, SwitchHec, BLANK() )
		formatString: 0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 166c55eb-c439-4312-9766-a7e24a2393a2

	measure 'SWITCH Vendas' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[QTD Vendas],
			    "R$",[R$ ROB],
			    "kg/Lt",[KGLT Vendas],
			    "Hec",[HEC Vendas]
			)
		formatString: #,0.00
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 77bfbde8-1841-4236-a46f-e49cf5ccce52

	measure 'HEC Pedidos de Compras Pendentes' =
			
			VAR SwitchHec =
			CALCULATE(
			    SUMX(
			        'Pedidos de Compras AXIA',
			        VAR txt =
			            TRIM(
			                SUBSTITUTE(
			                    RELATED('Dim Produto AXIA'[Und_Conversao_Lt_Hectar]), ",", "."
			                )
			            )
			        VAR num = IFERROR( VALUE( txt ), BLANK() )
			        RETURN
			            IF(
			                NOT ISBLANK(num) && num > 0,
			                'Pedidos de Compras AXIA'[KGLT_PENDENTE_FINAL] / num,
			                BLANK()
			            )
			    ),
			    'Dim Produto AXIA'[Nom_Marca] = "Corteva"
			)
			RETURN
			IF( SwitchHec > 0, SwitchHec, BLANK() )
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 5bc78f41-93e8-41db-b38e-ff36b6e577d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SWITCH Pedidos de Compras Pendentes' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[QTD Pedidos de Compras Pendentes],
			    "R$",[R$ Pedidos de Compras Pendentes],
			    "kg/Lt",[KGLT Pedidos de Compras Pendentes],
			    "Hec",[HEC Pedidos de Compras Pendentes]
			)
		formatString: 0.00
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: e2c9ec8f-aa96-4815-b069-62b4000cbca0

	measure 'KGLT Prox 30d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,1,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 8ddd1dde-3b45-4bfc-917b-c6043e8d8f21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Prox 30d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,1,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 79e34435-1e71-4d66-abd9-07f637661fa9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 30d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,1,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Análises
		lineageTag: d51b17dc-202c-40d2-af60-036cec97b92d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Prox 30d (Análises)' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Prox 30d (Análises)],
			                            "R$",[R$ Prox 30d (Análises)],
			                            "kg/Lt",[KGLT Prox 30d (Análises)],
			                            "Hec",[Hec Prox 30d (Análises)]
			                        )
		displayFolder: 3.Vendas\Análises
		lineageTag: d160cb73-7086-4394-9409-d11db1aaeb9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 60d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,2,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 89302453-9484-4ccf-9531-154fffc82816

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Prox 60d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,2,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: b91656bd-90b2-473d-9cca-dc362f23d5bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 60d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,2,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Análises
		lineageTag: 6d3915b8-5279-492c-b1b9-5d7a987ec4f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Prox 60d (Análises)' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Prox 60d (Análises)],
			                            "R$",[R$ Prox 60d (Análises)],
			                            "kg/Lt",[KGLT Prox 60d (Análises)],
			                            "Hec",[Hec Prox 60d (Análises)]
			                        )
		displayFolder: 3.Vendas\Análises
		lineageTag: 3e1a3ff7-6451-480d-b797-0940c64cddf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 90d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,3,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 3d4fcb39-523c-4486-8267-268504b227c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Prox 90d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,3,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 64429ad0-00b1-4da0-8a13-0de3fa2ae647

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 90d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,3,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Análises
		lineageTag: 0f02fd4a-efb5-4f76-a311-c68a774301d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Prox 90d (Análises)' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Prox 90d (Análises)],
			                            "R$",[R$ Prox 90d (Análises)],
			                            "kg/Lt",[KGLT Prox 90d (Análises)],
			                            "Hec",[Hec Prox 90d (Análises)]
			                        )
		displayFolder: 3.Vendas\Análises
		lineageTag: 28197e71-3567-4273-97b3-ad0c67b90022

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 120d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,4,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: fd782b79-40df-482a-a7a0-bf383758aa31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Prox 120d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,4,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: c39f510d-4576-41be-bd84-be8ea53eb04e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 120d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,4,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Análises
		lineageTag: d2321186-8675-487f-ad99-5b2a1013e689

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Prox 120d (Análises)' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Prox 120d (Análises)],
			                            "R$",[R$ Prox 120d (Análises)],
			                            "kg/Lt",[KGLT Prox 120d (Análises)],
			                            "Hec",[Hec Prox 120d (Análises)]
			                        )
		displayFolder: 3.Vendas\Análises
		lineageTag: 198a4f2a-d515-45bd-b333-0beda139fcf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 150d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,5,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 0325345c-93cc-40e1-9f91-e0d9164cea3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 150d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,5,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Análises
		lineageTag: 0df225a8-8c5b-44ec-bff2-bec618acf46c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Prox 150d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,5,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: 07043230-8ce4-46ed-943d-df7b6f35ba76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Prox 150d (Análises)' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Prox 150d (Análises)],
			                            "R$",[R$ Prox 150d (Análises)],
			                            "kg/Lt",[KGLT Prox 150d (Análises)],
			                            "Hec",[Hec Prox 150d (Análises)]
			                        )
		displayFolder: 3.Vendas\Análises
		lineageTag: 0bfddb45-7f49-419d-ae01-6543975ef1be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Prox 180d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,6,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: c4068051-54c1-4d2f-aa3b-ceb9b5b86f0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Prox 180d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,6,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Análises
		lineageTag: ff0a33bf-4942-4341-be68-5099f0e26a9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Prox 180d (Análises)' = SUMX(DATESINPERIOD('Dim Calendário'[Date],LASTDATE('Dim Calendário'[Date])-365,6,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Análises
		lineageTag: 9f3338ce-c6b4-4866-a946-cac2a995a743

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Prox 180d (Análises)' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Prox 180d (Análises)],
			                            "R$",[R$ Prox 180d (Análises)],
			                            "kg/Lt",[KGLT Prox 180d (Análises)],
			                            "Hec",[Hec Prox 180d (Análises)]
			                        )
		displayFolder: 3.Vendas\Análises
		lineageTag: eeb3192b-51c3-4a41-bc8f-9ae3b3616774

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Ult 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-60,2,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: ede02f20-4b89-4fb7-a717-7324b8c99ca4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Ult 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-60,2,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: fa7acc22-5f46-4679-a8e1-32b6c37f2cee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Ult 60d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-60,2,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 62818656-34d5-43be-9693-1dbb176126d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Ult 90d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-90,3,MONTH),[KGLT Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: c52818e7-58c6-4310-a8a9-fcf6dea24d67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hec Ult 90d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-90,3,MONTH),[HEC Vendas])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 9a44abc7-0950-4f26-ba99-9c530fdd9490

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Ult 90d' = SUMX(DATESINPERIOD('Dim Calendário'[Date],today()-90,3,MONTH),[R$ ROB])
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: d9ab9ec7-17db-4174-abbf-f84e0145e91b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Ult 60d' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Ult 60d],
			                            "R$",[R$ Ult 60d],
			                            "kg/Lt",[KGLT Ult 60d],
			                            "Hec",[Hec Ult 60d]
			                        )
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 81acae4a-687f-4000-8457-958d540efea3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch Ult 90d' =
			SWITCH(SELECTEDVALUE(Medidas[Switch Unidade]),
			                            "Un",[QTD Ult 90d],
			                            "R$",[R$ Ult 90d],
			                            "kg/Lt",[KGLT Ult 90d],
			                            "Hec",[Hec Ult 90d]
			                        )
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 0a59a151-658a-41dc-9678-c94b5a8dc75d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HEC Estoque Liquido & Compras (Análises)' = [HEC Estoque Bruto (Análises)]-[HEC F.Antecipados]+[HEC Pedidos de Compras Pendentes]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 89afb3a0-cd72-4d34-96bd-25caf5684e1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SWITCH Estoque Líquido & Compras (Análises)' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[QTD Estoque Liquido & Compras (Análises)],
			    "R$",[R$ Estoque Liquido (Análises)],
			    "kg/Lt",[KGLT Estoque Liquido & Compras (Análises)],
			    "Hec",[HEC Estoque Liquido & Compras (Análises)]
			)
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 4e333578-adb0-4090-844a-00d9917a3909

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R$ Estoque Liquido (Sem Compras) (Análises)' = [R$ Estoque Atual (Análises)]-[R$ F.Antecipados]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: d246454a-be24-4327-b6e8-52a3a39dc765

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Estoque Liquido & Compras (Análises)' = [KGLT Estoque Atual (Análises)]-[KGLT F.Antecipados]+[KGLT Pedidos de Compras Pendentes]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 2a1b59b0-62bf-41aa-8dc4-333736edba5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KGLT Estoque Liquido (Sem Compras) (Análises)' = [KGLT Estoque Atual (Análises)]-[KGLT F.Antecipados]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 7ad480f7-6005-410f-80d2-76fcd2d8aa9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HEC Estoque Liquido (Sem Compras) (Análises)' = [HEC Estoque Bruto (Análises)]-[HEC F.Antecipados]
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: d39987b3-670c-46d1-9baf-7addf30b1fa4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SWITCH Estoque Líquido (Análises)' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[QTD Estoque Liquido (Análises)],
			    "R$",[R$ Estoque Liquido (Sem Compras) (Análises)],
			    "kg/Lt",[KGLT Estoque Liquido (Sem Compras) (Análises)],
			    "Hec",[HEC Estoque Liquido (Sem Compras) (Análises)]
			)
		displayFolder: 1.Estoque\Estoque Atual
		lineageTag: 19fd49b2-c389-4ddd-b1d0-52c804d69fcd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure QTD_ENTREGUE = ```
			
			VAR DATA_ATUAL =
			    MAX(Compras[DATA_POSICAO])
			
			VAR QTD_ATUAL =
			    SUM(Compras[CUSTO_PENDENTE_FINAL])
			
			VAR PROXIMA_DATA =
			    CALCULATE(
			        MIN(Compras[DATA_POSICAO]),
			        FILTER(
			            ALLEXCEPT(
			                Compras,
			                Compras[NUM_PEDIDO],
			                Compras[CNPJ]
			            ),
			            Compras[DATA_POSICAO] > DATA_ATUAL
			        )
			    )
			
			VAR QTD_PROXIMA_DATA =
			    CALCULATE(
			        SUM(Compras[CUSTO_PENDENTE_FINAL]),
			        Compras[DATA_POSICAO] = PROXIMA_DATA,
			        ALLEXCEPT(
			            Compras,
			            Compras[NUM_PEDIDO],
			            Compras[CNPJ]
			        )
			    )
			
			VAR STATUS_PED =
			IF(
			    SELECTEDVALUE(Compras[STATUS]) = "Resíduo"
			        &&
			        CALCULATE(
			            MAX(Compras[CUSTO_PENDENTE_FINAL]),
			            FILTER(
			                ALLEXCEPT(Compras, Compras[NUM_PEDIDO]),
			                Compras[DATA_POSICAO]
			                    = CALCULATE(
			                        MAX(Compras[DATA_POSICAO]),
			                        ALLEXCEPT(Compras, Compras[NUM_PEDIDO])
			                    )
			            )
			        )
			        =
			        CALCULATE(
			            MAX(Compras[CUSTO_PENDENTE_FINAL]),
			            FILTER(
			                ALLEXCEPT(Compras, Compras[NUM_PEDIDO]),
			                Compras[DATA_POSICAO]
			                    = CALCULATE(
			                        MIN(Compras[DATA_POSICAO]),
			                        ALLEXCEPT(Compras, Compras[NUM_PEDIDO])
			                    )
			            )
			        ),
			    "Resíduo",
			    ""
			)
			
			
			RETURN
			IF(
			 STATUS_PED = "Resíduo" || QTD_ATUAL = QTD_PROXIMA_DATA || DATA_ATUAL = TODAY()-1,
			    BLANK(),
			    QTD_ATUAL - QTD_PROXIMA_DATA
			)
			
			
			```
		displayFolder: 8.S&OP
		lineageTag: 02b6439b-e143-403a-b013-42b50c89ceb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Leadtime Compras' = CALCULATE(Pedido)
		displayFolder: 6.Pedidos de Compra\Pendentes
		lineageTag: 8df4f0fb-7149-4514-b36a-1528c11608b3

	measure 'Custo Reposição R$' =
			
			VAR FILTROLINHA =
			    [QTD Estoque Bruto (Análises)] <> 0
			        || [QTD F.Antecipados] <> 0
			        || [QTD Pedidos de Compras Pendentes] <> 0
			
			RETURN
			IF(FILTROLINHA,
			    IF(
			        [R$ Estoque Atual (Análises)]<>0,
			        AVERAGE('Estoque Atual AXIA'[CUSTO_REPOSICAO]),
			        AVERAGE('Dim Custos'[CUSTO_REPOSICAO])
			    ),
			    BLANK()
			)
		displayFolder: 8.S&OP\Previsões
		lineageTag: 1bdfd41d-479b-4c2c-962c-0ed0107b51b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SWITCH Custo Unitário Estoque' =
			
			SWITCH(
			    SELECTEDVALUE(Medidas[Switch Unidade]),
			    "Un",[R$ Custo Médio Unitário],
			    "R$",1,
			    "kg/Lt",[KGLT Estoque Atual (Análises)],
			    "Hec",[HEC Estoque Bruto (Análises)]
			)
		displayFolder: 8.S&OP\Previsões
		lineageTag: e570ed09-a911-4aef-b882-5d16c618bb71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Erro (S&OP)' = ```
	/*
		📦 MIGRADO DO V3 | Erro de Previsão S&OP

		PROPÓSITO:
			Calcula o erro absoluto entre a quantidade vendida real e a
			demanda prevista pelo S&OP/Protheus. Métrica fundamental para
			avaliar acurácia das previsões de demanda.

		LÓGICA:
			1. Obtém quantidade vendida real (QTD Vendas)
			2. Obtém demanda prevista para 60 dias (Demanda S&OP/Protheus 60d)
			3. Calcula diferença (Real - Previsto)
			4. Valores positivos: Vendeu MAIS que previsto
			5. Valores negativos: Vendeu MENOS que previsto

		DEPENDÊNCIAS:
			- [QTD Vendas]: Quantidade total vendida (com ajuste de outliers)
			- [Demanda S&OP/Protheus 60d]: Previsão de demanda para próximos 60 dias

		ORIGEM:
			Modelo: S&OP Axia V3
			Tabela Original: Medidas (V3)
			Data Migração: 2026-02-03

		REGRA DE NEGÓCIO:
			- Usado em análises de acurácia de forecasting
			- Base para cálculo do WMAPE (%)

		AUTOR: Data Team - Migração V3→V2
		DATA: 2026-02-03
	*/
	[QTD Vendas] - [Demanda S&OP/Protheus 60d]
	```
		displayFolder: 8.S&OP\Previsões
		lineageTag: 9f5a8c7d-3b22-4c8e-9d3a-1a2b3c4d5e6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation Description = "📦 MIGRADO DO V3 | Calcula o erro de previsão subtraindo a demanda prevista da quantidade vendida real. Usado para análise de acurácia de previsões S&OP."

	measure 'WMAPE (%) (S&OP)' = ```
	/*
		📦 MIGRADO DO V3 | Weighted Mean Absolute Percentage Error

		PROPÓSITO:
			Calcula o erro percentual ponderado da previsão de demanda.
			Métrica chave (KPI) para avaliar acurácia do forecasting S&OP.

		LÓGICA:
			1. Obtém erro absoluto de previsão ([Erro (S&OP)])
			2. Obtém quantidade vendida real como base ([QTD Vendas])
			3. Divide erro pela quantidade vendida
			4. Usa DIVIDE para evitar divisão por zero
			5. Retorna BLANK se não houver vendas

		DEPENDÊNCIAS:
			- [Erro (S&OP)]: Diferença entre real e previsto
			- [QTD Vendas]: Quantidade vendida (denominador)

		ORIGEM: Modelo: S&OP Axia V3

		AUTOR: Data Team - Migração V3→V2
		DATA: 2026-02-03
	*/
	DIVIDE([Erro (S&OP)], [QTD Vendas])
	```
		displayFolder: 8.S&OP\Previsões
		formatString: 0.00%
		lineageTag: 4a7b6c5d-2e3f-4a1b-9c8d-0f1e2d3c4b5a

		annotation PBI_FormatHint = {"isDecimal":true}
		annotation Description = "📦 MIGRADO DO V3 | Weighted Mean Absolute Percentage Error. Calcula o percentual de erro da previsão dividindo o erro pela quantidade vendida. Métrica chave para avaliar acurácia de forecasting."

	measure 'Estoq. - Fat. Ante. - 60d (un)' = ```
	/*
		📦 MIGRADO DO V3 | POG 60 dias (Plano Operacional de Gestão)

		PROPÓSITO:
			Calcula a cobertura de estoque líquido considerando faturamentos
			antecipados dos próximos 60 dias. Usado para planejamento de
			reposição e análise de risco de ruptura de curto prazo.

		LÓGICA:
			1. Obtém estoque líquido atual (disponível)
			2. Obtém faturamentos antecipados para próximos 60 dias
			3. Calcula diferença (Estoque - Faturamentos Antecipados)

		DEPENDÊNCIAS:
			- [QTD Estoque Liquido (Análises)]: Estoque disponível atual
			- [QTD Prox 60d (Análises)]: Faturamentos antecipados 60 dias

		AUTOR: Data Team - Migração V3→V2
		DATA: 2026-02-03
	*/
	[QTD Estoque Liquido (Análises)] - [QTD Prox 60d (Análises)]
	```
		displayFolder: 8.S&OP\Estoques - POGs
		formatString: #,0
		lineageTag: b1c2d3e4-f5a6-4b7c-8d9e-0a1b2c3d4e5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation Description = "📦 MIGRADO DO V3 | Plano Operacional de Gestão (POG). Calcula a diferença entre estoque líquido atual e faturamentos antecipados dos próximos 60 dias. Usado para planejamento de cobertura de estoque."

	measure 'Estoq. - Fat. Ante. - 90d (un)' = ```
	/*
		📦 MIGRADO DO V3 | POG 90 dias (Plano Operacional de Gestão)

		PROPÓSITO:
			Calcula a cobertura de estoque líquido considerando faturamentos
			antecipados dos próximos 90 dias. Usado para planejamento de
			reposição de médio prazo e análise estratégica de estoque.

		LÓGICA:
			1. Obtém estoque líquido atual (disponível)
			2. Obtém faturamentos antecipados para próximos 90 dias
			3. Calcula diferença (Estoque - Faturamentos Antecipados)

		DEPENDÊNCIAS:
			- [QTD Estoque Liquido (Análises)]: Estoque disponível atual
			- [QTD Prox 90d (Análises)]: Faturamentos antecipados 90 dias

		AUTOR: Data Team - Migração V3→V2
		DATA: 2026-02-03
	*/
	[QTD Estoque Liquido (Análises)] - [QTD Prox 90d (Análises)]
	```
		displayFolder: 8.S&OP\Estoques - POGs
		formatString: #,0
		lineageTag: c6d5e4f3-2b1a-4c3d-9e8f-7a6b5c4d3e2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}
		annotation Description = "📦 MIGRADO DO V3 | Plano Operacional de Gestão (POG). Calcula a diferença entre estoque líquido atual e faturamentos antecipados dos próximos 90 dias. Usado para planejamento de cobertura de estoque de médio prazo."

	measure 'QTD Vendas (sem ajuste)' =
			
			CALCULATE(
			    SUM('Vendas Total AXIA'[QTD_DISP]),
			    FILTER(
			        'Vendas Total AXIA',
			        'Vendas Total AXIA'[FLG_REAL_SAIDA] = "REAL SAÍDA"
			    )
			)
		displayFolder: 3.Vendas\Vendas Geral
		lineageTag: 54d3e797-363d-40f4-b7ec-6ac33b3c8f38

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vencimento
		lineageTag: bafc413d-bbd6-4fc2-bdf7-9513ee889971
		summarizeBy: none
		isNameInferred
		sourceColumn: [Vencimento]
		sortByColumn: OrdemDias

		annotation SummarizationSetBy = Automatic

	column OrdemDias
		formatString: 0
		lineageTag: af737219-57ef-4518-a17c-474326628a3a
		summarizeBy: sum
		isNameInferred
		sourceColumn: [OrdemDias]

		annotation SummarizationSetBy = Automatic

	column 'Slow Moving'
		lineageTag: 2b58f2dd-3ec6-4d90-83a3-8a1073be178f
		summarizeBy: none
		isNameInferred
		sourceColumn: [Slow Moving]
		sortByColumn: OrdemDias

		annotation SummarizationSetBy = Automatic

	column 'Switch Unidade'
		lineageTag: d4d13783-f6c9-40a9-9235-04b11c1e70be
		summarizeBy: none
		isNameInferred
		sourceColumn: [Switch Unidade]
		sortByColumn: OrdemDias

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Vencimento", STRING,
				    "Slow Moving", STRING,
				    "Switch Unidade",STRING,
				    "OrdemDias", INTEGER,
				    {
				        { "Vencido", "<180 dias", "R$", 1 },
				        { "30 dias", "Entre 180 e 360 dias", "Un", 2 },
				        { "60 dias", ">360 dias", "kg/Lt", 3 },
				        { "90 dias", "4", "Hec", 4 },
				        { "120 dias", "5", "5", 5 },
				        { "150 dias", "6", "6", 6 },
				        { "180 dias", "7", "7", 7 },
				        { "+180 dias", "8", "8", 8 }
				    }
				)

	annotation PBI_Id = 8468a68937c4492bb73c359b5f7a0f14

