table 'Ruptura Diário'
	lineageTag: 63b6cf45-c283-4f31-9c6f-e87acdb58eef

	column DATA_POSICAO
		dataType: dateTime
		formatString: Short Date
		lineageTag: d95be9d7-9d0f-428f-b7b1-cb88effc0aa2
		summarizeBy: none
		sourceColumn: DATA_POSICAO

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CLASSIFICACAO_QBR
		dataType: string
		lineageTag: 4e83fe71-273f-4336-9f6e-0369fbaf9599
		summarizeBy: none
		sourceColumn: CLASSIFICACAO_QBR

		annotation SummarizationSetBy = Automatic

	column FILIAL_PLANEJAMENTO
		dataType: string
		lineageTag: 3f08760c-c6e2-40ad-afac-b1887c153680
		summarizeBy: none
		sourceColumn: FILIAL_PLANEJAMENTO

		annotation SummarizationSetBy = Automatic

	column PRODUTO_FINAL
		dataType: string
		lineageTag: 4bf89260-0794-475a-88eb-b2d5740fddd9
		summarizeBy: none
		sourceColumn: PRODUTO_FINAL

		annotation SummarizationSetBy = Automatic

	column CURVA_PRODUTO
		dataType: string
		lineageTag: 36a4891c-55d8-48b0-ac71-9c113823012e
		summarizeBy: none
		sourceColumn: CURVA_PRODUTO

		annotation SummarizationSetBy = Automatic

	column DSC_GRUPO
		dataType: string
		lineageTag: a8afca9a-3cfe-486f-8090-c7c260802bc6
		summarizeBy: none
		sourceColumn: DSC_GRUPO

		annotation SummarizationSetBy = Automatic

	column DSC_SUBGRUPO1
		dataType: string
		lineageTag: a8e960cd-074c-46b9-ac45-35e69239d82c
		summarizeBy: none
		sourceColumn: DSC_SUBGRUPO1

		annotation SummarizationSetBy = Automatic

	column DSC_SUBGRUPO2
		dataType: string
		lineageTag: 60ea8d6d-7383-486a-9dde-6245bc5fb298
		summarizeBy: none
		sourceColumn: DSC_SUBGRUPO2

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE_ESTOQUE
		dataType: string
		lineageTag: 0515c0e5-fcca-42ba-aa89-257b411f837c
		summarizeBy: none
		sourceColumn: QUANTIDADE_ESTOQUE

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE_FAT_ANTECIPADO
		dataType: string
		lineageTag: 468c8971-7813-4543-bd81-45f19752bd81
		summarizeBy: none
		sourceColumn: QUANTIDADE_FAT_ANTECIPADO

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE_PEDIDO_ABERTO
		dataType: string
		lineageTag: f25c6ada-5926-4f39-b5a7-c5bb2c78205e
		summarizeBy: none
		sourceColumn: QUANTIDADE_PEDIDO_ABERTO

		annotation SummarizationSetBy = Automatic

	column RUPTURA_DIARIA
		dataType: double
		formatString: #,0.00
		lineageTag: d63feb40-6522-4911-8533-6472de0a7155
		summarizeBy: sum
		sourceColumn: RUPTURA_DIARIA

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column CUSTO_RUPTURA_DIARIA
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: e9d5e13d-d193-48e6-bf51-8adad3bdd4ee
		summarizeBy: sum
		sourceColumn: CUSTO_RUPTURA_DIARIA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column RUPTURA_15
		dataType: double
		lineageTag: 56fb5b33-ecbe-4528-85be-d6d705cf3fd0
		summarizeBy: sum
		sourceColumn: RUPTURA_15

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RUPTURA_15D_CUSTO
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: ec75bae9-c653-4415-9258-0153670ffeca
		summarizeBy: sum
		sourceColumn: RUPTURA_15D_CUSTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column RUPTURA_30
		dataType: double
		lineageTag: 7db7dfdb-d1e0-4bad-97ba-4d2b1a636bd9
		summarizeBy: sum
		sourceColumn: RUPTURA_30

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RUPTURA_30D_CUSTO
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 73ef392b-8b17-4af6-bdcd-91bea00ec663
		summarizeBy: sum
		sourceColumn: RUPTURA_30D_CUSTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column CUSTO_FAT_ANTECIPADO
		dataType: double
		lineageTag: 110a0610-4002-4725-a187-a953fdc1f1f2
		summarizeBy: sum
		sourceColumn: CUSTO_FAT_ANTECIPADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CUSTO_PEDIDO_ABERTO
		dataType: double
		lineageTag: 0447137f-c111-4937-8bfb-4385ac0c58b8
		summarizeBy: sum
		sourceColumn: CUSTO_PEDIDO_ABERTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Custo Ruptura Acumulado' =
			
			CALCULATE (
			    SUM ( 'Ruptura Diário'[CUSTO_RUPTURA_DIARIA] ),
			    ALLEXCEPT (
			        'Ruptura Diário',
			        'Ruptura Diário'[PRODUTO_FINAL],
			        'Ruptura Diário'[FILIAL_PLANEJAMENTO],
			        'Ruptura Diário'[CURVA_PRODUTO]
			    )
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 11593119-d380-4c4d-bfbd-a6d11009a6ae
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column FILTRO_DATA =
			
			IF(TODAY()-2='Ruptura Diário'[DATA_POSICAO],1,BLANK())
		formatString: 0
		lineageTag: cf76dc69-cb8b-4e81-8690-75e9b39c0dba
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Ruptura Diário' = m
		mode: import
		source =
				let
				    // Conecta ao site SharePoint
				    Fonte = SharePoint.Contents("https://agroopps.sharepoint.com/sites/AgrolineCorporativo", [ApiVersion = 15]),
				    #"Documentos Partilhados" = Fonte{[Name="Documentos Partilhados"]}[Content],
				    #"03.Demand Planning" = #"Documentos Partilhados"{[Name="03.Demand Planning"]}[Content],
				    Coleta_Ruptura = #"03.Demand Planning"{[Name="Coleta_Ruptura"]}[Content],
				    // Filtra apenas os arquivos CSV
				    ArquivosCSV = Table.SelectRows(Coleta_Ruptura, each Text.EndsWith([Name], ".csv")),
				
				    // Lê o conteúdo de cada arquivo CSV
				    ConteudoCSV = Table.AddColumn(ArquivosCSV, "Dados", each Csv.Document([Content], [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.None])),
				    #"Dados Expandido" = Table.ExpandTableColumn(ConteudoCSV, "Dados", {"Column1"}, {"Dados.Column1"}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Dados Expandido", "Dados.Column1", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Dados.Column1.1", "Dados.Column1.2", "Dados.Column1.3", "Dados.Column1.4", "Dados.Column1.5", "Dados.Column1.6", "Dados.Column1.7", "Dados.Column1.8", "Dados.Column1.9", "Dados.Column1.10", "Dados.Column1.11", "Dados.Column1.12", "Dados.Column1.13", "Dados.Column1.14", "Dados.Column1.15", "Dados.Column1.16", "Dados.Column1.17", "Dados.Column1.18"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"Dados.Column1.1", type text}, {"Dados.Column1.2", type text}, {"Dados.Column1.3", type text}, {"Dados.Column1.4", type text}, {"Dados.Column1.5", type text}, {"Dados.Column1.6", type text}, {"Dados.Column1.7", type text}, {"Dados.Column1.8", type text}, {"Dados.Column1.9", type text}, {"Dados.Column1.10", type text}, {"Dados.Column1.11", type text}, {"Dados.Column1.12", type text}, {"Dados.Column1.13", type text}, {"Dados.Column1.14", type text}, {"Dados.Column1.15", type text}, {"Dados.Column1.16", type text}, {"Dados.Column1.17", type text}, {"Dados.Column1.18", type text}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Tipo Alterado",1),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Superiores Removidas",{"Content", "Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(
				    #"Colunas Removidas",
				    {
				        {"Dados.Column1.1",  "CLASSIFICACAO_QBR"},
				        {"Dados.Column1.2",  "FILIAL_PLANEJAMENTO"},
				        {"Dados.Column1.3",  "PRODUTO_FINAL"},
				        {"Dados.Column1.4",  "CURVA_PRODUTO"},
				        {"Dados.Column1.5",  "DSC_GRUPO"},
				        {"Dados.Column1.6",  "DSC_SUBGRUPO1"},
				        {"Dados.Column1.7",  "DSC_SUBGRUPO2"},
				        {"Dados.Column1.8",  "QUANTIDADE_ESTOQUE"},
				        {"Dados.Column1.9",  "QUANTIDADE_FAT_ANTECIPADO"},
				        {"Dados.Column1.10", "QUANTIDADE_PEDIDO_ABERTO"},
				        {"Dados.Column1.11", "RUPTURA_DIARIA"},
				        {"Dados.Column1.12", "CUSTO_RUPTURA_DIARIA"},
				        {"Dados.Column1.13", "RUPTURA_15"},
				        {"Dados.Column1.14", "RUPTURA_15D_CUSTO"},
				        {"Dados.Column1.15", "RUPTURA_30"},
				        {"Dados.Column1.16", "RUPTURA_30D_CUSTO"},
				        {"Dados.Column1.17", "CUSTO_FAT_ANTECIPADO"},
				        {"Dados.Column1.18", "CUSTO_PEDIDO_ABERTO"}
				    }
				),
				    #"Texto Extraído Entre os Delimitadores" = Table.TransformColumns(#"Colunas Renomeadas", {{"Name", each Text.BetweenDelimiters(_, "Ruptura_", ".csv"), type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Texto Extraído Entre os Delimitadores",".",",",Replacer.ReplaceText,{"RUPTURA_15D_CUSTO"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",".",",",Replacer.ReplaceText,{"RUPTURA_30D_CUSTO"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1",".",",",Replacer.ReplaceText,{"CUSTO_RUPTURA_DIARIA"}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Valor Substituído2",".",",",Replacer.ReplaceText,{"CUSTO_FAT_ANTECIPADO"}),
				    #"Valor Substituído4" = Table.ReplaceValue(#"Valor Substituído3",".",",",Replacer.ReplaceText,{"CUSTO_PEDIDO_ABERTO"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído4",{{"CUSTO_RUPTURA_DIARIA", type number}, {"RUPTURA_15D_CUSTO", type number}, {"RUPTURA_30D_CUSTO", type number}, {"CUSTO_FAT_ANTECIPADO", type number}, {"CUSTO_PEDIDO_ABERTO", type number}}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Tipo Alterado1",{{"Name", "DATA_POSICAO"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Renomeadas1", each not Text.Contains([FILIAL_PLANEJAMENTO], "Tabela Rupturas NL[FILIAL_PLANEJAMENTO]"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

